/**
 * 动力电池与车辆电气标准索引（仅题录与工程摘要，不含标准正文）。
 * 状态与版本复核日期：2026-09-01。使用前仍须在发布机构官网核验最新状态。
 */
(function (global) {
  'use strict';
  const CN = 'https://openstd.samr.gov.cn/bzgk/std/std_list?p.p1=0&p.p2=';
  const ISO = 'https://www.iso.org/search.html?q=';
  const IEC = 'https://webstore.iec.ch/searchform&q=';
  const UN = 'https://unece.org/transport/vehicle-regulations-wp29/standards/addenda-1958-agreement-regulations-81-100';
  const LV = 'https://www.dakks.de/files/data/as/pdf/D-PL-17186-01-01.pdf';
  const LV_EXTENDED = 'https://www.edag.com/fileadmin/Zertifikate/DAkkS_-_Akkreditierung/DIN_EN_ISO_IEC_17025/Flexibel_Akkreditierte_Verfahrensliste_Fulda_de_de.pdf';
  const USCAR = 'https://uscar.org/ewcap/test-specs/';
  const USCAR_REVISIONS = 'https://uscar.org/ewcap/spec-revision-letters/';
  const cn = (number) => CN + encodeURIComponent(number);
  const iso = (number) => ISO + encodeURIComponent(number);
  const iec = (number) => IEC + encodeURIComponent(number);

  global.ELECTRICAL_STANDARD_LIBRARY = {
    verifiedAt: '2026-09-01',
    records: [
      // ---- 动力电池：中国 ----
      { no:'GB 38031-2025', system:'GB', topic:'动力电池', status:'现行', level:'电池包/系统', title:'电动汽车用动力蓄电池安全要求',
        summary:'动力电池安全的核心强制性国家标准。围绕热扩散、机械冲击、振动、挤压、外部火烧、过充过放、短路、温度冲击等整车与电池系统风险建立要求和试验框架。',
        focus:['安全边界','热扩散','机械滥用','电气滥用'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=282F76EA982A69B46595DB00702CC8C2' },
      { no:'GB/T 31467-2023', system:'GB', topic:'动力电池', status:'现行', level:'电池包/系统', title:'电动汽车用锂离子动力电池包和系统电性能试验方法',
        summary:'用于评价电池包和系统的容量、能量、功率、效率、能量保持、存储及循环等电性能。适合编制DV/PV试验计划和供应商性能对标。',
        focus:['容量能量','功率能力','效率','循环性能'], source:'https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=BD0DF56EEE7B59422D05C1296869B5FE' },
      { no:'GB/T 31484-2015', system:'GB', topic:'动力电池', status:'现行', level:'电芯/模组', title:'电动汽车用动力蓄电池循环寿命要求及试验方法',
        summary:'规定单体和模块的标准循环与工况循环寿命评价思路。用于寿命指标定义时应结合使用窗口、温度、倍率及终止条件。',
        focus:['循环寿命','工况循环','容量保持'], source:cn('GB/T 31484-2015') },
      { no:'GB/T 31486-2024', system:'GB', topic:'动力电池', status:'现行', level:'电芯/模组', title:'电动汽车用动力蓄电池电性能要求及试验方法',
        summary:'面向单体与模块的容量、倍率、荷电保持、能量效率和温度适应性等基础电性能。与电池包系统级试验标准的对象层级不同。',
        focus:['基础电性能','倍率','温度适应性'], source:cn('GB/T 31486-2024') },
      { no:'GB/T 34013-2017', system:'GB', topic:'动力电池', status:'现行', level:'电芯/模组/电池包', title:'电动汽车用动力蓄电池产品规格尺寸',
        summary:'给出动力电池单体、模块和标准箱等产品规格尺寸系列，用于平台化、互换性和包装边界规划；不等同于结构强度或安全验证标准。',
        focus:['规格尺寸','平台化','边界设计'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=649BA022374AF0C35EF13CFB826CD106' },
      { no:'GB/T 34013-2026', system:'GB', topic:'动力电池', status:'即将实施', level:'电芯/模组/电池包', title:'电动汽车用动力蓄电池产品规格尺寸',
        summary:'已发布的新版本，将于2027-02-01实施并接替2017版。平台或零件生命周期跨越实施日期时，应提前开展尺寸系列、接口和存量设计的版本切换评估。',
        focus:['版本切换','规格尺寸','2027实施'], source:cn('GB/T 34013-2026') },
      { no:'GB/T 34014-2017', system:'GB', topic:'动力电池', status:'现行', level:'全生命周期', title:'汽车动力蓄电池编码规则',
        summary:'建立动力蓄电池产品编码结构与标识规则，用于生产、装车、维修、退役和回收全生命周期追溯。',
        focus:['编码','追溯','全生命周期'], source:cn('GB/T 34014-2017') },
      { no:'GB/T 38661-2020', system:'GB', topic:'动力电池', status:'现行', level:'BMS/系统', title:'电动汽车用电池管理系统技术条件',
        summary:'关注BMS的电压、温度、电流、SOC等测量与估算功能，以及绝缘监测、故障诊断、通信和环境适应性。项目中需继续分解为可量化系统需求。',
        focus:['BMS','SOC','绝缘监测','诊断通信'], source:cn('GB/T 38661-2020') },

      // ---- 动力电池：国际/法规 ----
      { no:'UN Regulation No. 100 Rev.3', system:'UNECE', topic:'动力电池', status:'现行', level:'整车/REESS', title:'电驱动车辆动力系统安全及可充电储能系统型式批准',
        summary:'UNECE车辆型式批准法规。覆盖触电防护、可充电储能系统（REESS）安全、热事件及相关整车验证；面向出口车型时应按目标市场法规版本建立合规矩阵。',
        focus:['型式批准','REESS','触电防护','热事件'], source:UN },
      { no:'UN GTR No. 20', system:'UNECE', topic:'动力电池', status:'现行', level:'整车/REESS', title:'电动汽车安全全球技术法规（EVS）',
        summary:'建立电动汽车与REESS安全的全球协调技术框架，涉及在用安全、碰撞后电安全、热扩散和涉水等；各缔约方落地法规可能不同。',
        focus:['全球技术法规','碰撞后安全','热扩散'], source:'https://unece.org/transport/standards/transport/vehicle-regulations-wp29/global-technical-regulations-gtrs' },
      { no:'UN Manual of Tests and Criteria, 38.3', system:'UNECE', topic:'动力电池', status:'现行', level:'运输', title:'锂电池运输试验（UN 38.3）',
        summary:'锂电池运输前的高度模拟、温度、振动、冲击、外短路、撞击/挤压、过充和强制放电试验依据。它解决运输准入问题，不能替代车辆使用安全验证。',
        focus:['运输安全','UN 38.3','试验概要'], source:'https://unece.org/transport/dangerous-goods/rev7-files' },
      { no:'ISO 12405-4:2018', system:'ISO', topic:'动力电池', status:'现行', level:'电池包/系统', title:'锂离子动力电池包和系统性能试验',
        summary:'面向高功率和高能量应用的电池包/系统性能、可靠性与电功能试验。电芯级试验通常转向IEC 62660系列。',
        focus:['性能','可靠性','电功能'], source:'https://www.iso.org/standard/71407.html' },
      { no:'IEC 62660-1:2018', system:'IEC', topic:'动力电池', status:'现行', level:'电芯', title:'电动道路车辆用锂离子电芯—性能试验',
        summary:'规定推进用二次锂离子电芯的容量、功率、能量、存储及循环等性能试验，是电芯选型和横向比较的重要基础。',
        focus:['电芯性能','容量','功率','循环'], source:iec('IEC 62660-1:2018') },
      { no:'IEC 62660-2:2018', system:'IEC', topic:'动力电池', status:'现行', level:'电芯', title:'电动道路车辆用锂离子电芯—可靠性和滥用试验',
        summary:'评价电芯在振动、机械冲击、挤压、温度及电气滥用等条件下的可靠性和耐受能力，不能直接代表电池包安全表现。',
        focus:['可靠性','机械滥用','电气滥用'], source:iec('IEC 62660-2:2018') },
      { no:'IEC 62660-3:2022', system:'IEC', topic:'动力电池', status:'现行', level:'电芯', title:'电动道路车辆用锂离子电芯—安全要求',
        summary:'规定推进用电芯和电芯块的安全性能试验及接受准则，前提是电芯在制造商规定的电压、电流和温度工作区间内被电池系统正确使用。',
        focus:['电芯安全','接受准则','工作区间'], source:'https://webstore.iec.ch/en/publication/65084' },

      // ---- 换电 ----
      { no:'GB/T 40032-2021', system:'GB', topic:'换电系统', status:'现行', level:'整车/换电系统', title:'电动汽车换电安全要求',
        summary:'换电车辆和换电过程的核心国家标准，覆盖一般要求、换电接口、锁止与监控、换电操作、故障防护及试验验证。需与电池包、整车电安全和换电站标准联合使用。',
        focus:['换电安全','接口','锁止','故障防护'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=7F8FEA35CAE388B191FB39D5A4951B00' },
      { no:'GB/T 40098-2021', system:'GB', topic:'换电系统', status:'现行', level:'换电电池包', title:'电动汽车更换用动力蓄电池箱编码规则',
        summary:'统一换电电池箱编码与识别信息，支持车辆、换电站、电池资产和运营平台之间的追溯与数据关联。',
        focus:['电池箱编码','资产追溯','互操作'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=075B761373D14F0046ADA1EDA10A9B8F' },
      { no:'GB/T 32879-2025', system:'GB', topic:'换电系统', status:'现行', level:'换电连接器', title:'电动汽车更换用电池箱连接器',
        summary:'针对可更换电池箱连接器的结构、插拔、载流、温升、绝缘、机械与环境性能。设计时尤其关注浮动补偿、寿命、污染和带载分断边界。',
        focus:['换电连接器','插拔寿命','浮动补偿','温升'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=09415D50E5BB60A19E47A36324AFB161' },
      { no:'GB/T 33341-2025', system:'GB', topic:'换电系统', status:'现行', level:'换电机构', title:'电动汽车快换电池箱架',
        summary:'聚焦快换电池箱架的结构、锁止、定位、强度和环境适应性，为箱体—车架机械接口及耐久验证提供依据。',
        focus:['箱架','定位锁止','结构强度','耐久'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=6D71ECD4797C846304307F97A169D2E2' },
      { no:'GB/T 29772-2024', system:'GB', topic:'换电系统', status:'现行', level:'换电站', title:'电动汽车电池更换站通用技术要求',
        summary:'规定换电站的系统构成、功能、设备、土建接口、安全防护和运行条件，是车辆/电池之外规划站端边界的重要总则。',
        focus:['换电站','系统构成','站端安全'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=1E10B1C888E0774248FDEC2C00C845EB' },
      { no:'GB/T 32895-2025', system:'GB', topic:'换电系统', status:'现行', level:'车辆/电池箱通信', title:'电动汽车快换电池箱通信协议',
        summary:'统一车辆与快换电池箱之间的通信信息和交互，为识别、状态确认、故障处理与互操作提供协议基础。',
        focus:['换电通信','状态交互','互操作'], source:cn('GB/T 32895-2025') },
      { no:'GB/T 45098-2024', system:'GB', topic:'换电系统', status:'现行', level:'运营服务', title:'营运纯电动汽车换电服务技术要求',
        summary:'面向营运车辆换电服务过程、设备、人员、数据和安全管理，偏运营服务边界，不替代产品设计与型式试验标准。',
        focus:['换电运营','服务流程','安全管理'], source:cn('GB/T 45098-2024') },
      { no:'GB/T 29317-2021', system:'GB', topic:'换电系统', status:'现行', level:'术语', title:'电动汽车充换电设施术语',
        summary:'统一充电、换电、设备、接口和运营相关术语，适合在SOR、技术协议、测试报告中作为名词定义基础。',
        focus:['术语','系统边界','文档一致性'], source:cn('GB/T 29317-2021') },
      { no:'IEC 62840-1:2025', system:'IEC', topic:'换电系统', status:'现行', level:'换电站/系统', title:'电动汽车换电系统—通用与指南',
        summary:'给出换电系统总体架构、分类和互操作指导，覆盖自动/辅助/手动以及可手持更换电池，电压范围最高至1000 V AC或1500 V DC。',
        focus:['系统架构','互操作','SBS/HBS'], source:'https://webstore.iec.ch/en/publication/66398' },
      { no:'IEC 62840-2:2025', system:'IEC', topic:'换电系统', status:'现行', level:'换电站/系统', title:'电动汽车换电系统—安全要求',
        summary:'规定换电系统的触电、机械、过载短路、EMC、通信安全、标识和说明等要求，应与IEC 62840-1:2025配合使用。',
        focus:['系统安全','触电防护','机械安全','通信安全'], source:'https://webstore.iec.ch/en/publication/66390' },
      { no:'IEC PAS 62840-3:2021', system:'IEC', topic:'换电系统', status:'现行', level:'低压可移除电池', title:'可移除RESS换电系统的特别安全与互操作要求',
        summary:'面向额定电压不超过120 V DC的可移除RESS及其换电系统，补充功率传输、通信和电网连接要求；项目应用前应复核其PAS状态及后续替代版本。',
        focus:['可移除RESS','低压换电','互操作'], source:'https://webstore.iec.ch/en/publication/31939' },

      // ---- 电气架构 ----
      { no:'GB 18384-2025', system:'GB', topic:'电气架构', status:'现行', level:'整车', title:'电动汽车安全要求',
        summary:'整车电安全强制性国家标准。涉及高压标识、直接/间接接触防护、绝缘电阻、电位均衡、残余电压、功能安全相关故障防护及涉水等要求。',
        focus:['整车电安全','触电防护','绝缘','电位均衡'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=36F2726143479B33E76BACB6BD2AF4B0' },
      { no:'GB/T 34590（全系列）', system:'GB', topic:'电气架构', status:'现行', level:'E/E系统', title:'道路车辆 功能安全',
        summary:'ISO 26262对应的中国国家标准系列，覆盖安全生命周期、ASIL、概念阶段、系统/硬件/软件开发、支持过程和量产运维。它处理由E/E系统故障引起的风险，不覆盖全部预期功能不足风险。',
        focus:['功能安全','ASIL','安全生命周期'], source:cn('GB/T 34590') },
      { no:'GB/T 28046（全系列）', system:'GB', topic:'电气架构', status:'现行', level:'电气电子部件', title:'道路车辆 电气及电子设备的环境条件和试验',
        summary:'覆盖电气负荷、机械负荷、气候负荷、化学负荷等汽车电子环境试验。应按安装位置、供电网络和部件边界选择试验严酷度。',
        focus:['环境可靠性','电气负荷','机械气候负荷'], source:cn('GB/T 28046') },
      { no:'GB/T 21437.2-2021', system:'GB', topic:'电气架构', status:'现行', level:'低压电气系统', title:'道路车辆 由传导和耦合引起的电骚扰 第2部分：沿电源线瞬态传导发射和抗扰性',
        summary:'低压供电网络瞬态脉冲测试的重要依据，用于电源端口抗扰度与发射验证。测试等级和脉冲选择应来自整车电源网络分析。',
        focus:['瞬态脉冲','低压供电','传导抗扰'], source:cn('GB/T 21437.2-2021') },
      { no:'GB/T 33014（全系列）', system:'GB', topic:'电气架构', status:'现行', level:'电气电子部件', title:'道路车辆 电气/电子部件对窄带辐射电磁能的抗扰性试验方法',
        summary:'规定暗室、TEM小室、大电流注入、带状线等部件级射频抗扰度方法。项目需依据接口、线束、频段和整车要求选取方法及等级。',
        focus:['EMC','射频抗扰','BCI','暗室法'], source:cn('GB/T 33014') },
      { no:'GB 34660-2017', system:'GB', topic:'电气架构', status:'现行', level:'整车/部件', title:'道路车辆 电磁兼容性要求和试验方法',
        summary:'道路车辆整车及电子电气组件的强制性EMC要求，涉及发射与抗扰度。进行新车型合规策划时应检查是否有公告、实施规则或新版本衔接。',
        focus:['EMC合规','发射','抗扰'], source:cn('GB 34660-2017') },
      { no:'ISO 6469-1:2019', system:'ISO', topic:'电气架构', status:'现行', level:'整车/RESS', title:'电驱动车辆安全规范—可充电储能系统',
        summary:'规定车载可充电储能系统的安全要求，涵盖系统设计、人员保护和典型运行风险；需与ISO 6469其他部分联合建立整车安全条目。',
        focus:['RESS','系统安全','整车集成'], source:iso('ISO 6469-1:2019') },
      { no:'ISO 6469-2:2022', system:'ISO', topic:'电气架构', status:'现行', level:'整车', title:'电驱动车辆安全规范—车辆运行安全',
        summary:'关注车辆运行状态、故障提示、驱动系统行为和操作安全，用于整车功能状态机及驾驶员交互相关安全需求。',
        focus:['运行安全','状态机','故障提示'], source:iso('ISO 6469-2:2022') },
      { no:'ISO 6469-3:2021', system:'ISO', topic:'电气架构', status:'现行', level:'高压系统', title:'电驱动车辆安全规范—电气安全',
        summary:'针对电压等级B回路的触电和热危害防护，包括绝缘、直接/间接接触、防护措施及验证。新版正在修订时，项目应核对目标市场认可版本。',
        focus:['高压安全','绝缘','触电防护'], source:'https://www.iso.org/standard/81746.html' },
      { no:'ISO 6469-4:2015', system:'ISO', topic:'电气架构', status:'现行', level:'碰撞后整车', title:'电驱动车辆安全规范—碰撞后电气安全',
        summary:'规定碰撞后高压系统触电风险控制和验证方法，包括电压、电能、物理防护及绝缘等判据。',
        focus:['碰撞后安全','残余电压','物理防护'], source:iso('ISO 6469-4:2015') },
      { no:'ISO 26262（全系列）', system:'ISO', topic:'电气架构', status:'现行', level:'E/E系统', title:'Road vehicles—Functional safety',
        summary:'汽车E/E功能安全国际基础标准。工程输出通常包括HARA、安全目标、FSC/TSC、硬件指标、软件安全活动、确认措施和安全案例。',
        focus:['功能安全','HARA','ASIL','安全案例'], source:iso('ISO 26262') },
      { no:'ISO 21498-1/-2:2021', system:'ISO', topic:'电气架构', status:'现行', level:'高压供电', title:'电驱动车辆电压等级B系统和部件的电气规范与试验',
        summary:'第1部分定义电压等级B子系统/部件的电气规格，第2部分给出试验方法，适合高压架构的稳态、瞬态、纹波、状态转换和验证条件定义。',
        focus:['高压供电','电气负荷','部件验证'], source:iso('ISO 21498') },
      { no:'UNECE Regulation No. 10 Rev.6', system:'UNECE', topic:'电气架构', status:'现行', level:'整车/ESA', title:'车辆电磁兼容型式批准法规',
        summary:'UNECE市场整车和电子组件（ESA）EMC型式批准依据。需依据车型、充电模式和部件属性识别适用条款、限值及认证流程。',
        focus:['EMC型式批准','整车','ESA'], source:'https://unece.org/transport/vehicle-regulations-wp29/standards/addenda-1958-agreement-regulations-1-20' },

      // ---- 连接器 ----
      { no:'GB/T 37133-2025', system:'GB', topic:'高低压连接器', status:'现行', level:'车载高压连接系统', title:'电动汽车用高压连接系统',
        summary:'覆盖高压线束与连接器组成的连接系统，重点包括电气、机械、环境、屏蔽、密封、温升、耐久和安全要求。已替代2018版，项目应避免继续引用旧名称。',
        focus:['高压连接器','高压线束','温升','屏蔽密封'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=857A7DFFFCA97FC6C04A943646BCE830' },
      { no:'GB/T 20234.1-2023', system:'GB', topic:'高低压连接器', status:'现行', level:'充电连接装置', title:'电动汽车传导充电用连接装置 第1部分：通用要求',
        summary:'充电插头、插座、车辆连接器、车辆插座和电缆组件的一般结构、电气、机械、温升、防护与试验要求，是各接口分册的通用基础。',
        focus:['充电连接器','通用要求','温升','防护'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=5A456919C33E2C9041B843AB3D36AB67' },
      { no:'GB/T 20234.2-2015', system:'GB', topic:'高低压连接器', status:'现行', level:'交流充电接口', title:'电动汽车传导充电用连接装置 第2部分：交流充电接口',
        summary:'规定交流充电接口的功能定义、触头布置、尺寸和连接要求。与2023版通用要求配套使用时应关注版本间引用关系。',
        focus:['交流充电','接口尺寸','触头定义'], source:cn('GB/T 20234.2-2015') },
      { no:'GB/T 20234.3-2023', system:'GB', topic:'高低压连接器', status:'现行', level:'直流充电接口', title:'电动汽车传导充电用连接装置 第3部分：直流充电接口',
        summary:'规定直流充电接口的结构、功能定义、触头布置和尺寸要求，是常规直流充电车辆端与设备端互配基础。',
        focus:['直流充电','接口互配','触头定义'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=5928F89DE3DB6FD3FDDC06E709FCC4A2' },
      { no:'GB/T 20234.4-2023', system:'GB', topic:'高低压连接器', status:'现行', level:'大功率直流充电', title:'电动汽车传导充电用连接装置 第4部分：大功率直流充电接口',
        summary:'面向大功率直流充电耦合器，处理更高功率下的接口、热管理、互锁与安全要求。需与充电系统及通信协议一并设计。',
        focus:['大功率充电','热管理','互锁'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=FA36759EA1B57E9F92260A1DBF6D0E76' },
      { no:'ISO 8092-2:2023', system:'ISO', topic:'高低压连接器', status:'现行', level:'车载低压连接器', title:'车载线束连接—定义、试验方法和一般性能要求',
        summary:'车载单极/多极低压线束连接器的常用国际系列标准之一，关注接触电阻、机械保持、环境耐久和连接可靠性；具体适用电压与结构边界需查对应分册。',
        focus:['低压连接器','接触可靠性','环境耐久'], source:iso('ISO 8092-2:2023') },
      { no:'ISO 8092-5:2021', system:'ISO', topic:'高低压连接器', status:'现行', level:'车载线束连接器', title:'车载线束连接—连接器操作的试验方法和通用性能要求',
        summary:'针对装车后仅在维修维护时断开的单极和多极连接，定义术语、试验方法与一般性能要求；不适用于电子设备内部连接。',
        focus:['连接器操作','维修插拔','通用性能'], source:'https://www.iso.org/standard/72528.html' },
      { no:'IEC 62196-1:2025', system:'IEC', topic:'高低压连接器', status:'现行', level:'充电连接器', title:'电动汽车传导充电用插头、插座、车辆连接器和车辆插座—通用要求',
        summary:'IEC充电连接器系列通用基础，涵盖额定值、结构、温升、接触材料、机械耐久、污染和安全试验。使用时应配套对应AC/DC接口分册。',
        focus:['充电连接器','通用要求','温升','机械耐久'], source:iec('IEC 62196-1:2025') },
      { no:'IEC 62196-2:2025', system:'IEC', topic:'高低压连接器', status:'现行', level:'交流充电接口', title:'交流插针和插套附件的尺寸兼容性要求',
        summary:'规定交流充电接口的标准化结构和尺寸兼容性，主要解决附件的物理接口与互配，不替代第1部分通用安全试验。',
        focus:['交流接口','尺寸兼容','互配'], source:iec('IEC 62196-2:2025') },
      { no:'IEC 62196-3:2022', system:'IEC', topic:'高低压连接器', status:'现行', level:'直流充电接口', title:'直流及交直流插针和插套车辆耦合器的尺寸兼容性要求',
        summary:'规定多种直流及组合式车辆耦合器配置和尺寸要求，是不同地区DC接口方案识别、互配和出口设计的重要索引。',
        focus:['直流接口','组合接口','尺寸兼容'], source:iec('IEC 62196-3:2022') },
      { no:'IEC 60664-1:2020', system:'IEC', topic:'高低压连接器', status:'现行', level:'绝缘配合', title:'低压供电系统设备的绝缘配合—原则、要求和试验',
        summary:'电气间隙、爬电距离、过电压类别、污染等级、材料组别和海拔修正的基础标准之一。产品标准有专门要求时应优先执行产品标准。',
        focus:['电气间隙','爬电距离','绝缘配合'], source:iec('IEC 60664-1:2020') },
      { no:'IEC 60529:1989+A1:1999+A2:2013', system:'IEC', topic:'高低压连接器', status:'现行', level:'外壳防护', title:'外壳防护等级（IP代码）',
        summary:'定义IP防尘防水等级及试验。连接器应明确配合/非配合、带附件、安装状态等测试条件，不能只写一个IP等级而忽略样品状态。',
        focus:['IP等级','防尘防水','配合状态'], source:iec('IEC 60529') },
      { no:'IEC 61851-1:2017', system:'IEC', topic:'高低压连接器', status:'现行', level:'充电系统', title:'电动汽车传导充电系统—通用要求',
        summary:'充电系统总体模式、功能、电气安全和控制导引基础。连接器机械接口、充电设备及通信协议需分别结合IEC 62196、IEC 61851其他分册和ISO 15118。',
        focus:['传导充电','控制导引','系统安全'], source:iec('IEC 61851-1:2017') },
      { no:'ISO 15118-20:2022', system:'ISO', topic:'高低压连接器', status:'现行', level:'充电通信', title:'车网通信接口—第二代网络层与应用层要求',
        summary:'面向充电通信的网络与应用层，包括AC/DC、双向功率传输及自动认证等用例。它定义通信，不定义连接器机械尺寸。',
        focus:['充电通信','V2G','双向充电','PnC'], source:iso('ISO 15118-20:2022') },

      // ---- 连接器：德国 LV / OEM 体系 ----
      { no:'LV 214:2010-03', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'车载低压连接器', title:'机动车连接器试验规范',
        summary:'德国整车厂联合形成的车载连接器基础验证框架，覆盖尺寸与材料、接触电阻、插拔和保持力、机械负荷、温湿度、化学介质、密封及耐久等试验组。LV文本本身不等于项目放行版本，供应商应取得目标OEM当前企业标准及偏差清单。',
        focus:['LV体系','低压连接器','试验组','OEM派生'], source:LV },
      { no:'LV 214-1（试验矩阵）', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'低压连接器/DV计划', title:'机动车连接器试验矩阵',
        summary:'用于把LV 214试验项目组合为适用于端子、护套、密封和连接器系统的验证矩阵。工程上应先定义密封等级、温度等级、振动安装位置、线径和镀层，再按OEM派生标准选取样本量与序列。',
        focus:['试验矩阵','样本量','DV/PV','环境等级'], source:LV },
      { no:'LV 214-2:2008-01', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'端子—导线连接', title:'机动车接触连接的慢动作试验',
        summary:'针对压接区在导线横向/轴向缓慢运动下的微电阻变化与接触稳定性，常用于暴露压接、应力释放和线束出口设计引起的瞬断或阻值波动。不同OEM已有更新的企业版，必须核对项目指定版本。',
        focus:['Slow Motion','压接','微动','动态电阻'], source:LV },
      { no:'LV 214-3（试验序列）', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'连接器系统/DV计划', title:'机动车连接器试验序列',
        summary:'将机械、电气、气候、密封与耐久项目组织成有前后老化关系的试验序列。不能把单项合格简单等同于完整序列合格，项目中应保留样件分组、前后测量点和失效判据。',
        focus:['试验序列','老化前后','连接器系统','失效判据'], source:LV },
      { no:'LV 215-1:2013-02', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'车载高压连接器', title:'机动车高压接触系统性能要求',
        summary:'高压连接系统的要求侧文件，关注额定电压/电流、温升与降额、接触电阻、屏蔽连续性、绝缘、耐压、防触电、互锁、插拔安全和机械编码等设计边界，并与LV 215-2验证文件配套使用。',
        focus:['高压连接器','性能要求','HVIL','屏蔽与绝缘'], source:LV },
      { no:'LV 215-2:2013-02', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'车载高压连接器', title:'机动车高压接触系统试验规范',
        summary:'在LV 214基础上补充高压连接器验证，包括绝缘电阻、耐电压、爬电/电气间隙、温升降额、屏蔽衰减、接触防护、互锁时序、密封、振动和高压端子机械性能等。试验条件应以目标OEM现行企业版为准。',
        focus:['高压试验','耐压绝缘','降额曲线','屏蔽','IP2X'], source:LV },
      { no:'LV 215:2016-11', system:'LV', topic:'高低压连接器', status:'OEM版本核验', level:'车载高压连接系统', title:'机动车高压连接系统要求与试验（后续整合版）',
        summary:'工程资料中常见的后续整合版本，将高压接触系统的设计要求和验证项目集中管理。旧项目仍可能引用LV 215-1/-2或对应VW、BMW、Mercedes-Benz企业标准；应按客户SOR确认哪一版本具有合同效力。',
        focus:['高压连接系统','整合版本','版本映射','客户SOR'], source:LV },
      { no:'LV 112-3:2011-12', system:'LV', topic:'高低压连接器', status:'配套规范', level:'导线/端子选型', title:'车用导线载流能力确定',
        summary:'连接器温升与降额校核的配套导线规范，讨论导体截面、材料、绝缘、环境温度、布置和散热对载流能力的影响。不能仅用端子额定电流替代导线—端子—连接器组合的热验证。',
        focus:['载流能力','导线温升','端子匹配','降额'], source:LV_EXTENDED },
      { no:'LV 216-1:2015-10', system:'LV', topic:'高低压连接器', status:'配套规范', level:'非屏蔽高压线缆', title:'车用高压单芯/非屏蔽线缆要求与试验',
        summary:'高压连接器尾端电缆选型的配套规范，覆盖导体、绝缘、机械、热、化学和高压特有性能。连接系统DV应把线缆外径、弯曲、拉脱、密封圈压缩和温度等级作为同一边界管理。',
        focus:['高压线缆','非屏蔽','密封匹配','尾端设计'], source:LV_EXTENDED },
      { no:'LV 216-2:2016', system:'LV', topic:'高低压连接器', status:'配套规范', level:'屏蔽高压线缆', title:'车用屏蔽高压护套线缆要求与试验',
        summary:'面向屏蔽高压线缆及电驱连接应用，关注屏蔽结构、电气与机械耐久、环境老化和护套性能。选用高压连接器时需联合核对屏蔽压接结构、转移阻抗/屏蔽性能及线缆—连接器兼容性。',
        focus:['高压线缆','屏蔽','EMC','屏蔽压接'], source:LV_EXTENDED },

      // ---- 连接器：北美 USCAR / EWCAP 体系 ----
      { no:'SAE/USCAR-2', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'车载低压连接器', title:'汽车电气连接器系统性能规范',
        summary:'USCAR连接器验证的核心通用规范，覆盖端子和连接器系统的机械、电气、环境、密封、振动、温湿度、化学介质、耐久及连续性监测。具体项目仍需由OEM定义温度、密封、振动等应用等级。',
        focus:['连接器验证','密封/非密封','环境耐久','连续性监测'], source:USCAR },
      { no:'SAE/USCAR-12', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'连接器设计', title:'电气连接器设计要求',
        summary:'面向接口和结构设计的准则，涉及极化/防错、锁止、CPA/TPA、端子保护、装配服务性及尺寸设计；官方修订信还补充48 V与高压连接器的默认设计假设、爬电距离和电气间隙等内容。',
        focus:['设计准则','CPA/TPA','防错锁止','48V/HV'], source:USCAR_REVISIONS },
      { no:'SAE/USCAR-17', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'射频/同轴连接器', title:'汽车射频连接器系统性能规范',
        summary:'针对汽车RF/同轴连接器系统，在通用环境耐久基础上增加阻抗、驻波比、插入损耗、屏蔽泄漏等高频指标，适用于天线、雷达及射频链路验证。',
        focus:['RF连接器','同轴','插入损耗','屏蔽泄漏'], source:USCAR },
      { no:'SAE/USCAR-18', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'射频连接器设计', title:'USCAR-17射频连接器补充规范',
        summary:'作为USCAR-17的配套补充，处理汽车射频连接器接口和设计相关要求。使用时应与USCAR-17及项目指定接口图纸一起引用，并核对当前修订关系。',
        focus:['RF补充','接口设计','USCAR-17配套'], source:USCAR },
      { no:'SAE/USCAR-21', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'导线—端子压接', title:'导线至端子电气压接性能规范',
        summary:'建立压接样件准备、压接高度/宽度、截面分析、拉脱力、电阻、热冲击和环境老化等验证框架，是连接器端子压接工艺开发、过程窗口和变更再验证的重要依据。',
        focus:['压接','截面分析','拉脱力','工艺窗口'], source:USCAR },
      { no:'SAE/USCAR-25', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'装配与维修人机工程', title:'电气连接的人机工程规范',
        summary:'用于评估连接器插拔、锁止、解锁、维修和装配操作的人机工程边界，避免只满足机械保持力却造成工位操作负担或售后不可维修。',
        focus:['人机工程','插拔操作','维修性','装配力'], source:USCAR },
      { no:'SAE/USCAR-26', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'接地连接', title:'电气接地附件试验程序',
        summary:'针对车身/设备接地点及其附件的电气、机械和环境可靠性验证。关注接触电阻、紧固、表面处理、腐蚀和电流承载，不应把普通信号端子规则直接套用于大电流接地。',
        focus:['接地点','接触电阻','紧固','腐蚀'], source:USCAR },
      { no:'SAE/USCAR-30', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'USB连接系统', title:'汽车USB连接性能规范',
        summary:'面向车载USB连接系统的机械、电气、信号和环境性能验证，适用于信息娱乐与数据接口。除连接可靠性外，还需结合目标USB代际和信号完整性要求。',
        focus:['USB','数据连接','信号完整性','环境验证'], source:USCAR },
      { no:'SAE/USCAR-37', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'车载高压连接器', title:'SAE/USCAR-2高压连接器性能补充规范',
        summary:'在USCAR-2基础上增加高压连接器特有的绝缘、耐压、电气间隙/爬电、触电防护、互锁及高压环境验证。官方变更已把应用电压边界扩展到1000 V，并与USCAR-2现行章节重新对齐。',
        focus:['高压连接器','1000V','耐压绝缘','HVIL','触电防护'], source:USCAR_REVISIONS },
      { no:'SAE/USCAR-38', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'线束超声焊接', title:'超声焊接导线终端性能规范',
        summary:'用于超声焊导线终端和连接点的工艺与性能验证，关注几何、拉力、电阻、热与环境老化。适用于线束分支或大电流导线连接，但具体材料组合和焊接窗口仍需过程验证。',
        focus:['超声焊','导线终端','工艺验证','电阻'], source:USCAR },
      { no:'SAE/USCAR-44', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'连接器/线束固定', title:'汽车线束保持夹性能规范',
        summary:'验证线束及连接器固定夹的保持、装配、机械和环境性能。连接器振动边界与夹点距离、线束质量和布置强相关，应与整车安装状态联合考虑。',
        focus:['线束固定夹','保持力','安装状态','振动边界'], source:USCAR },
      { no:'SAE/USCAR-45', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'导线—导线焊接', title:'焊接式导线对导线接头性能规范',
        summary:'面向焊接式线束拼接点的机械、电气和环境耐久验证，适合与压接拼接、超声焊方案进行工艺边界区分，并建立截面、拉力和电阻控制计划。',
        focus:['导线拼接','焊接','拉力','过程控制'], source:USCAR },
      { no:'SAE/USCAR-49', system:'USCAR', topic:'高低压连接器', status:'官方目录', level:'微型同轴连接器', title:'微型汽车同轴连接器性能规范',
        summary:'面向紧凑型汽车同轴连接器的高频和环境性能要求，兼顾小型化接口的机械保持、阻抗、插损、回损与屏蔽性能，常用于摄像头、雷达和高速数据链路。',
        focus:['微型同轴','摄像头/雷达','回损','小型化'], source:USCAR },
      { no:'SAE/USCAR-53', system:'USCAR', topic:'高低压连接器', status:'官方修订信息', level:'工业通信连接器', title:'汽车工业通信连接器性能规范',
        summary:'USCAR官方修订目录列出的工业通信连接规范，面向车载工业通信/高速数据应用。正式引用前应从EWCAP核对规格是否已正式发布、当前版本和受控获取方式。',
        focus:['工业通信','高速数据','版本核验'], source:USCAR_REVISIONS },

      // ---- 历史版本：默认隐藏，用于识别旧图纸/旧报告 ----
      { no:'GB/T 37133-2018', system:'GB', topic:'高低压连接器', status:'已废止', level:'车载高压连接系统', title:'电动汽车用高压大电流线束和连接器技术要求',
        summary:'历史版本，已由GB/T 37133-2025替代。仅用于识别旧项目引用，不应直接用于新项目定版。',
        focus:['历史版本','已被替代'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=4B5113FF023AEAC6695AFC524D4D427A' },
      { no:'GB 18384-2020', system:'GB', topic:'电气架构', status:'已废止', level:'整车', title:'电动汽车安全要求',
        summary:'历史强制标准，已由GB 18384-2025替代。旧项目变更时需评估新旧要求和实施日期，而不是简单替换标准号。',
        focus:['历史版本','版本过渡'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=DA9BDFC1903FA2258AD614D6E8B0CDEF' },
      { no:'GB/T 31467.1/.2/.3-2015', system:'GB', topic:'动力电池', status:'已废止', level:'电池包/系统', title:'动力蓄电池包和系统测试系列（历史版本）',
        summary:'三个2015分册均已废止。电性能项目优先查GB/T 31467-2023，安全项目转向GB 38031现行版本。',
        focus:['历史版本','已被替代'], source:'https://openstd.samr.gov.cn/bzgk/std/std_list?p.p1=0&p.p2=GBT%2F31467&p.p90=circulation_date&p.p91=desc' },
      { no:'GB/T 31486-2015', system:'GB', topic:'动力电池', status:'已废止', level:'电芯/模组', title:'动力蓄电池电性能要求及试验方法（历史版本）',
        summary:'已由GB/T 31486-2024替代，仅用于旧项目追溯。新项目应按2024版重新核对试验对象、条件和判据。',
        focus:['历史版本','已被替代'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=C6710DC541FB39A797587D74805D7425' },
      { no:'GB/T 32879-2016', system:'GB', topic:'换电系统', status:'已废止', level:'换电连接器', title:'电动汽车更换用电池箱连接器通用技术要求（历史版本）',
        summary:'已由GB/T 32879-2025替代，仅用于旧连接器图纸和既有项目追溯。',
        focus:['历史版本','已被替代'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=8E70FA637EC8DE40D4EEBA7C1C9A05A6' },
      { no:'GB/T 33341-2016', system:'GB', topic:'换电系统', status:'已废止', level:'换电机构', title:'电动汽车快换电池箱架通用技术要求（历史版本）',
        summary:'已由GB/T 33341-2025替代，仅用于旧项目追溯。',
        focus:['历史版本','已被替代'], source:'https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=2532FB6D07F63E360BE922508B275E9D' },
    ],
  };
})(window);
