const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true,args:['--allow-file-access-from-files']});
  const page=await browser.newPage({viewport:{width:1700,height:1100},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(()=>ElectricalToolkit.open('schematic'));
  await page.waitForSelector('#schDiagram');assert.equal(await page.locator('.sch-component-editor').count(),4);assert.equal(await page.locator('.sch-wires tbody tr').count(),6);assert.equal(await page.locator('.sch-wire-label').count(),6);assert.ok(await page.locator('.sch-palette-item').count()>=20);assert.equal(await page.locator('.sch-wires').evaluate(el=>getComputedStyle(el).borderSpacing),'0px 10px');assert.equal(await page.locator('.sch-wires tbody tr').first().locator('td').first().evaluate(el=>getComputedStyle(el).borderLeftWidth),'4px');assert.equal(await page.locator('.sch-edit-grid').count(),1);assert.equal(await page.locator('#schToggleGrid').evaluate(el=>el.classList.contains('active')),true);assert.equal(await page.locator('#schToggleSnap').evaluate(el=>el.classList.contains('active')),true);await page.locator('#schToggleGrid').click();assert.equal(await page.locator('.sch-edit-grid').count(),0);await page.locator('#schToggleGrid').click();assert.equal(await page.locator('.sch-edit-grid').count(),1);if(process.env.SCHEMATIC_SCREENSHOT)await page.locator('#schCanvasPanel').screenshot({path:process.env.SCHEMATIC_SCREENSHOT});
  assert.equal(await page.locator('#schConnectionStatus').textContent(),'1 个Pin未连接');
  const demoCan=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections.find(w=>w.id==='w4'));assert.equal(demoCan.from,'pin:p_bmu_canh');assert.equal(demoCan.pairFrom,'pin:p_bmu_canl');assert.equal(demoCan.targets[0].to,'pin:p_lv_canh');assert.equal(demoCan.targets[0].pairTo,'pin:p_lv_canl');assert.equal(await page.locator('[data-wire-id="w4"] .sch-can-endpoint').count(),4);assert.equal(await page.locator('[data-wire-id="w4"] [data-endpoint-role="pairFrom"]').count(),3);assert.equal(await page.locator('[data-wire-branch="w4:t4"] .sch-can-high').count(),1);assert.equal(await page.locator('[data-wire-branch="w4:t4"] .sch-can-low').count(),1);
  await page.locator('#schAddCanWire').click();const blankTwisted=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections.at(-1));assert.equal(blankTwisted.type,'can');assert.equal(blankTwisted.from,'');assert.equal(blankTwisted.pairFrom,'');assert.equal(blankTwisted.targets[0].to,'');assert.equal(await page.locator('.sch-wires tbody tr').last().evaluate(el=>el.classList.contains('sch-can-incomplete')),true);await page.locator('.sch-wires tbody tr').last().locator('[data-delete-wire]').click();
  const canvasBeforeComponents=await page.evaluate(()=>{const canvas=document.querySelector('#schCanvasPanel'),components=document.querySelector('#schComponents');return Boolean(canvas.compareDocumentPosition(components)&Node.DOCUMENT_POSITION_FOLLOWING);});assert.ok(canvasBeforeComponents);
  assert.equal(await page.locator('.sch-endpoint-picker').first().locator('select').count(),3);assert.equal(await page.locator('.sch-wires option',{hasText:'高压驱动线路'}).count(),0);assert.equal((await page.locator('#schComponents').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length)),2);assert.equal((await page.locator('#schStandaloneDevices').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length)),2);assert.ok(await page.locator('#schEntities .sch-component-editor').evaluateAll(cards=>cards.every(card=>card.scrollWidth<=card.clientWidth+1)));if(process.env.ENTITIES_SCREENSHOT)await page.locator('#schEntities').screenshot({path:process.env.ENTITIES_SCREENSHOT});
  const keyboardBefore=await page.evaluate(()=>{const c=ElectricalToolkit.get('schematic').captureDraft().components.find(x=>x.id==='cmp_edm');return{x:c.x,y:c.y};});await page.locator('[data-move-component="cmp_edm"]').dispatchEvent('pointerdown',{clientX:500,clientY:300});await page.locator('[data-move-component="cmp_edm"]').dispatchEvent('pointerup',{clientX:500,clientY:300});assert.equal(await page.locator('[data-drag-component="cmp_edm"]').evaluate(el=>el.classList.contains('sch-selected')),true);await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowDown');const keyboardAfter=await page.evaluate(()=>{const c=ElectricalToolkit.get('schematic').captureDraft().components.find(x=>x.id==='cmp_edm');return{x:c.x,y:c.y};});assert.equal(keyboardAfter.x,keyboardBefore.x+10);assert.equal(keyboardAfter.y,keyboardBefore.y+1);await page.locator('#schDiagram .sheet').dispatchEvent('pointerdown',{clientX:20,clientY:20});assert.equal(await page.locator('.sch-selected').count(),0);await page.keyboard.press('ArrowLeft');assert.deepEqual(await page.evaluate(()=>{const c=ElectricalToolkit.get('schematic').captureDraft().components.find(x=>x.id==='cmp_edm');return{x:c.x,y:c.y};}),keyboardAfter);
  const svg=await page.locator('#schDiagram').innerHTML();assert.match(svg,/EDM 电源分配单元/);assert.match(svg,/Twisted_Pair/);assert.match(svg,/主继电器/);assert.match(svg,/SHUNT/);assert.match(svg,/LEGEND/);assert.match(svg,/REV/);assert.match(svg,/sch-twist-mark/);assert.match(svg,/sch-wire-label-bg/);assert.match(svg,/#b97718/);assert.match(svg,/data-resize-component/);assert.equal(await page.locator('[data-endpoint-key^="device:d_mainrelay:"]').count(),4);assert.ok(await page.locator('.sch-wire-hit').count()>0);assert.equal(await page.locator('[data-add-control]').count(),0);assert.equal(await page.locator('.sch-wire').first().evaluate(el=>getComputedStyle(el).pointerEvents),'none');assert.ok(await page.evaluate(()=>Boolean(document.querySelector('[data-drag-component="cmp_edm"]').compareDocumentPosition(document.querySelector('[data-wire-branch="w1:t1"]'))&Node.DOCUMENT_POSITION_FOLLOWING)),'wires must render above component fills');assert.ok(await page.locator('.sch-wire-label').evaluateAll(labels=>labels.every(label=>{const rect=label.querySelector('rect'),gap=Number(label.dataset.lineY)-Number(rect.getAttribute('y'))-Number(rect.getAttribute('height'));return gap>=4&&gap<=6;})), 'wire information must stay immediately above its own line');
  const edmColorSelect=page.locator('[data-component-editor="cmp_edm"] select[data-component-field="color"]');assert.ok(await edmColorSelect.locator('option').count()>=15);await edmColorSelect.selectOption('#dbe8f0');assert.equal(await page.locator('[data-drag-component="cmp_edm"] .sch-component-body').getAttribute('fill'),'#dbe8f0');await page.locator('[data-component-editor="cmp_edm"] input[data-component-field="color"]').fill('#cdeeff');assert.equal(await page.locator('[data-drag-component="cmp_edm"] .sch-component-body').getAttribute('fill'),'#cdeeff');await page.locator('[data-component-editor="cmp_edm"] [data-device-id="d_mainrelay"] select[data-device-field="color"]').selectOption('#e4deeb');assert.equal(await page.locator('[data-drag-component="cmp_edm"] .sch-relay-glyph rect').first().getAttribute('fill'),'#e4deeb');await page.locator('[data-component-editor="cmp_edm"] [data-device-id="d_mainrelay"] input[data-device-field="color"]').fill('#ffe0b2');assert.equal(await page.locator('[data-drag-component="cmp_edm"] .sch-relay-glyph rect').first().getAttribute('fill'),'#ffe0b2');
  assert.equal(await page.locator('#schSheetSize option').count(),4);assert.equal(await page.locator('#schZoom').inputValue(),'100');const a3ComponentWidth=await page.locator('[data-move-component="cmp_edm"]').getAttribute('width');await page.locator('#schSheetSize').selectOption('A0');assert.equal(await page.locator('#schDiagram').getAttribute('viewBox'),'0 0 3960 2546');assert.equal(await page.locator('#schDiagram').getAttribute('width'),'3960');assert.equal(await page.locator('[data-move-component="cmp_edm"]').getAttribute('width'),a3ComponentWidth);assert.match(await page.locator('#schDiagram').innerHTML(),/font:600 22px/);await page.locator('#schZoom').fill('50');await page.locator('#schZoom').dispatchEvent('input');assert.equal(Math.round((await page.locator('#schDiagram').boundingBox()).width),1980);await page.locator('#schZoomFit').click();assert.ok(Number(await page.locator('#schZoom').inputValue())<50);await page.locator('#schZoom').fill('100');await page.locator('#schZoom').dispatchEvent('input');await page.locator('#schSheetSize').selectOption('A3');assert.equal(await page.locator('#schDiagram').getAttribute('viewBox'),'0 0 1400 900');
  const routeBefore=await page.locator('[data-wire-branch="w1:t1"] path').first().getAttribute('d');await page.locator('[data-wire-segment="w1:t1"].h').nth(1).evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:x,clientY:y}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:x,clientY:y+45}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:x,clientY:y+45}));});assert.ok(await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections[0].targets[0].waypoints.length>0));assert.ok(await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections[0].targets[0].waypoints.every(p=>p.x%10===0&&p.y%10===0)));assert.notEqual(await page.locator('[data-wire-branch="w1:t1"] path').first().getAttribute('d'),routeBefore);
  await page.locator('#schFreeze').click();assert.ok(await page.locator('#schCanvasPanel').evaluate(el=>el.classList.contains('frozen')));await page.locator('#schFreeze').click();assert.ok(!(await page.locator('#schCanvasPanel').evaluate(el=>el.classList.contains('frozen'))));
  const beforeWidth=Number(await page.locator('[data-move-component="cmp_edm"]').getAttribute('width'));await page.locator('[data-resize-component="cmp_edm"]').evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:x,clientY:y}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:x+45,clientY:y+25}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:x+45,clientY:y+25}));});assert.ok(Number(await page.locator('[data-move-component="cmp_edm"]').getAttribute('width'))>beforeWidth);
  const pinCount=page.locator('[data-pin-count]').first();await pinCount.fill('5');const pinViewBefore=await page.evaluate(()=>{const input=document.querySelector('[data-pin-count]'),canvas=document.querySelector('#schCanvas'),palette=document.querySelector('#schPalette'),wires=document.querySelector('.sch-wire-scroll'),component=document.querySelectorAll('[data-component-editor]')[1],group=document.querySelectorAll('[data-palette-group]')[1];component.open=false;group.open=false;canvas.scrollLeft=120;canvas.scrollTop=75;palette.scrollTop=90;wires.scrollLeft=180;input.focus({preventScroll:true});window.scrollTo(0,input.getBoundingClientRect().top+window.scrollY-220);return{windowY:window.scrollY,canvasLeft:canvas.scrollLeft,canvasTop:canvas.scrollTop,paletteTop:palette.scrollTop,wiresLeft:wires.scrollLeft};});await pinCount.dispatchEvent('change');await page.waitForTimeout(50);assert.equal(await page.locator('.sch-component-editor').first().locator('.sch-connector').first().locator('.sch-pin').count(),5);const pinViewAfter=await page.evaluate(()=>({windowY:window.scrollY,canvasLeft:document.querySelector('#schCanvas').scrollLeft,canvasTop:document.querySelector('#schCanvas').scrollTop,paletteTop:document.querySelector('#schPalette').scrollTop,wiresLeft:document.querySelector('.sch-wire-scroll').scrollLeft,focus:document.activeElement.matches('[data-pin-count]'),componentOpen:document.querySelectorAll('[data-component-editor]')[1].open,paletteOpen:document.querySelectorAll('[data-palette-group]')[1].open}));assert.ok(Math.abs(pinViewAfter.windowY-pinViewBefore.windowY)<=2);assert.equal(pinViewAfter.canvasLeft,pinViewBefore.canvasLeft);assert.equal(pinViewAfter.canvasTop,pinViewBefore.canvasTop);assert.equal(pinViewAfter.paletteTop,pinViewBefore.paletteTop);assert.equal(pinViewAfter.wiresLeft,pinViewBefore.wiresLeft);assert.equal(pinViewAfter.focus,true);assert.equal(pinViewAfter.componentOpen,false);assert.equal(pinViewAfter.paletteOpen,false);
  await page.locator('[data-pin-field="no"]').first().evaluate(el=>{const dt=new DataTransfer();dt.setData('text/plain','1\tHV_POS\t正极输出\n2\tHV_NEG\t负极输出\n3\tHV_AUX\t辅助输出');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true}));});assert.equal(await page.locator('[data-pin-field="definition"]').nth(2).inputValue(),'HV_AUX');
  const firstConnector=page.locator('.sch-component-editor').first().locator('.sch-connector').first();assert.equal(await firstConnector.locator('[data-pin-field="pairGroup"]').first().isDisabled(),true);await firstConnector.locator('[data-pin-field="no"]').nth(3).evaluate(el=>{const dt=new DataTransfer();dt.setData('text/plain','4\tSENSE_P\t采样正\t是\t12\n5\tSENSE_N\t采样负\t是\t12');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true}));});assert.equal(await firstConnector.locator('[data-pin-field="twisted"]').nth(3).isChecked(),true);assert.equal(await firstConnector.locator('[data-pin-field="pairGroup"]').nth(3).inputValue(),'12');assert.equal(await firstConnector.locator('.sch-twisted-error').count(),0);await firstConnector.locator('[data-pin-field="twisted"]').nth(4).click();assert.equal(await firstConnector.locator('[data-pin-field="pairGroup"]').nth(4).isDisabled(),true);assert.equal(await firstConnector.locator('.sch-twisted-error').count(),1);await firstConnector.locator('[data-pin-field="twisted"]').nth(3).click();assert.equal(await firstConnector.locator('.sch-twisted-error').count(),0);
  await page.locator('[data-add-target]').first().click();assert.equal(await page.locator('.sch-wires tbody tr').first().locator('.sch-target').count(),2);assert.equal(await page.locator('.sch-wire-label').count(),6);
  await page.locator('[data-add-device]').first().click();assert.ok(await page.locator('.sch-device-row').count()>=4);
  await page.locator('#schAddExternal').click();assert.equal(await page.locator('.sch-component-editor').count(),5);await page.locator('#schAddWire').click();assert.equal(await page.locator('.sch-wires tbody tr').count(),7);
const jsonPromise=page.waitForEvent('download');await page.locator('#schExportJson').click();const jsonDownload=await jsonPromise;const jsonPath=path.join(root,'schematic-test.json');await jsonDownload.saveAs(jsonPath);const data=JSON.parse(fs.readFileSync(jsonPath,'utf8'));assert.equal(data.schemaVersion,8);assert.equal(data.components.length,5);assert.equal(data.connections.length,7);assert.equal(data.components.find(c=>c.id==='cmp_edm').color,'#cdeeff');assert.equal(data.components.find(c=>c.id==='cmp_edm').devices.find(d=>d.id==='d_mainrelay').color,'#ffe0b2');fs.unlinkSync(jsonPath);
  const svgPromise=page.waitForEvent('download');await page.locator('#schExportSvg').click();const svgDownload=await svgPromise;const svgPath=path.join(root,'schematic-test.svg');await svgDownload.saveAs(svgPath);const svgText=fs.readFileSync(svgPath,'utf8');assert.match(svgText,/viewBox="0 0 1400 900"/);assert.match(svgText,/stroke="#f5a400"/);assert.match(svgText,/fill="#cdeeff"/);assert.match(svgText,/fill="#ffe0b2"/);assert.doesNotMatch(svgText,/高压驱动线路/);assert.doesNotMatch(svgText,/data-resize-component/);assert.doesNotMatch(svgText,/data-wire-segment/);assert.doesNotMatch(svgText,/<g class="sch-edit-grid"/);fs.unlinkSync(svgPath);
  await page.evaluate(()=>{window.print=()=>{window.__schematicPrinted=true;};});await page.locator('#schExportPdf').click();await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__schematicPrinted),true);assert.equal(await page.locator('#schPrint svg').count(),1);
  await page.evaluate(()=>{const item=document.querySelector('[data-palette-type="relay"]'),canvas=document.querySelector('#schCanvas'),dt=new DataTransfer(),r=canvas.getBoundingClientRect();item.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));canvas.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientX:r.left+r.width*.55,clientY:r.top+r.height*.55}));canvas.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt,clientX:r.left+r.width*.55,clientY:r.top+r.height*.55}));});assert.equal(await page.locator('.sch-standalone-device').count(),1);assert.equal(await page.locator('#schStandaloneDevices .sch-device-editor').count(),1);const relayState=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().components.find(c=>c.type==='device'));assert.equal(relayState.x%10,0);assert.equal(relayState.y%10,0);assert.equal(relayState.connectors.flatMap(k=>k.pins).length,4);assert.deepEqual(relayState.connectors.flatMap(k=>k.pins).map(p=>p.no),['1','2','A1','A2']);assert.equal(relayState.w,116);assert.equal(relayState.h,92);assert.equal(await page.locator(`[data-drag-component="${relayState.id}"] [data-endpoint-key]`).count(),4);assert.equal(await page.locator(`[data-drag-component="${relayState.id}"] .sch-relay-glyph`).count(),1);await page.locator(`[data-component-editor="${relayState.id}"] select[data-component-field="color"]`).selectOption('#e4deeb');assert.equal(await page.locator(`[data-drag-component="${relayState.id}"] .sch-relay-glyph rect`).first().getAttribute('fill'),'#e4deeb');await page.locator(`[data-component-editor="${relayState.id}"] input[data-component-field="color"]`).fill('#d1c4e9');assert.equal(await page.locator(`[data-drag-component="${relayState.id}"] .sch-relay-glyph rect`).first().getAttribute('fill'),'#d1c4e9');assert.match(await page.locator(`[data-drag-component="${relayState.id}"] .sch-device-hit`).getAttribute('style'),/fill:#d1c4e9/);if(process.env.RELAY_SCREENSHOT)await page.locator(`[data-drag-component="${relayState.id}"]`).screenshot({path:process.env.RELAY_SCREENSHOT});
  const directBefore=await page.locator('.sch-wires tbody tr').count();await page.locator('#schCanvas').scrollIntoViewIfNeeded();await page.evaluate(()=>{const state=ElectricalToolkit.get('schematic').captureDraft(),device=state.components.find(c=>c.type==='device'),from=document.querySelector(`[data-endpoint-key="pin:${device.connectors[0].pins[0].id}"] circle`),to=document.querySelector('[data-endpoint-key="pin:p_bmu_kl30"] circle'),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),ax=a.left+a.width/2,ay=a.top+a.height/2,bx=b.left+b.width/2,by=b.top+b.height/2;from.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:ax,clientY:ay}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:bx,clientY:by}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:bx,clientY:by}));});assert.equal(await page.locator('.sch-wires tbody tr').count(),directBefore+1);assert.equal((await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft())).connections.length,directBefore+1);
  const moved=await page.evaluate(()=>{const s=ElectricalToolkit.get('schematic').captureDraft(),device=s.components.find(c=>c.type==='device'),wire=s.connections.at(-1);return{deviceId:device.id,x:device.x,branch:`${wire.id}:${wire.targets[0].id}`};}),deviceRouteBefore=await page.locator(`[data-wire-branch="${moved.branch}"] path`).first().getAttribute('d');await page.locator(`[data-move-component="${moved.deviceId}"]`).evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:x,clientY:y}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:x+55,clientY:y+25}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:x+55,clientY:y+25}));});assert.ok((await page.evaluate(id=>ElectricalToolkit.get('schematic').captureDraft().components.find(c=>c.id===id).x,moved.deviceId))>moved.x);assert.notEqual(await page.locator(`[data-wire-branch="${moved.branch}"] path`).first().getAttribute('d'),deviceRouteBefore);await page.locator(`[data-resize-component="${moved.deviceId}"]`).evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:x,clientY:y}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:x-500,clientY:y-500}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:x-500,clientY:y-500}));});const compactRelay=await page.evaluate(id=>ElectricalToolkit.get('schematic').captureDraft().components.find(c=>c.id===id),moved.deviceId);assert.equal(compactRelay.w,96);assert.equal(compactRelay.h,78);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'crossing-test'},components:[{id:'a',name:'A',type:'component',x:100,y:100,w:160,h:100,connectors:[{id:'ca',name:'J1',side:'right',pins:[{id:'pa',no:'1',definition:'A'}]}],devices:[]},{id:'b',name:'B',type:'component',x:600,y:100,w:160,h:100,connectors:[{id:'cb',name:'J2',side:'left',pins:[{id:'pb',no:'1',definition:'B'}]}],devices:[]},{id:'c',name:'C',type:'component',x:300,y:350,w:160,h:100,connectors:[{id:'cc',name:'J3',side:'top',pins:[{id:'pc',no:'1',definition:'C'}]}],devices:[]},{id:'d',name:'D',type:'component',x:300,y:20,w:160,h:80,connectors:[{id:'cd',name:'J4',side:'bottom',pins:[{id:'pd',no:'1',definition:'D'}]}],devices:[]}],connections:[{id:'h',from:'pin:pa',to:'pin:pb',type:'lv',gauge:'1 mm²'},{id:'v',from:'pin:pd',to:'pin:pc',type:'power12',gauge:'1 mm²'}],revisions:[]}));assert.match(await page.locator('#schCanvas #schDiagram').innerHTML(),/A6 6/);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'ground-test'},components:[{id:'g',name:'接地',type:'device',symbolType:'ground',x:300,y:120,w:150,h:104,connectors:[{id:'gin',name:'输入端',side:'left',pins:[{id:'g1',no:'1',definition:'IN'}]},{id:'gout',name:'输出端',side:'right',pins:[{id:'g2',no:'2',definition:'OUT'}]}],devices:[]}],connections:[],revisions:[]}));assert.equal(await page.locator('[data-drag-component="g"] [data-endpoint-key]').count(),1);assert.equal((await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().components[0].connectors.length)),1);const groundGeometry=await page.locator('[data-drag-component="g"]').evaluate(el=>({cx:el.querySelector('[data-endpoint-key] circle').getAttribute('cx'),cy:el.querySelector('[data-endpoint-key] circle').getAttribute('cy'),path:el.querySelector('path').getAttribute('d')}));assert.match(groundGeometry.path,new RegExp(`M${groundGeometry.cx} ${groundGeometry.cy}V`));assert.equal(await page.locator('[data-component-editor="g"] [data-add-connector]').isDisabled(),true);if(process.env.GROUND_SCREENSHOT)await page.locator('[data-drag-component="g"]').screenshot({path:process.env.GROUND_SCREENSHOT});
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({schemaVersion:5,meta:{title:'legacy-relay'},components:[{id:'legacy-relay',name:'旧继电器',type:'device',symbolType:'relay',x:200,y:120,w:150,h:104,connectors:[{id:'old-in',name:'输入',side:'left',pins:[{id:'old-p1',no:'1',definition:'主触点输入'}]},{id:'old-out',name:'输出',side:'right',pins:[{id:'old-p2',no:'2',definition:'主触点输出'}]}],devices:[]}],connections:[],revisions:[]}));const migratedRelay=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().components[0]);assert.equal(migratedRelay.w,116);assert.equal(migratedRelay.h,92);assert.equal(migratedRelay.connectors.flatMap(k=>k.pins).length,4);assert.equal(await page.locator('[data-drag-component="legacy-relay"] [data-endpoint-key]').count(),4);
await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({schemaVersion:6,meta:{title:'legacy-can'},components:[{id:'legacy-src',name:'源',type:'component',x:100,y:100,w:180,h:130,connectors:[{id:'legacy-js',name:'J1',side:'right',pins:[{id:'legacy-sh',no:'1',definition:'CAN_H'},{id:'legacy-sl',no:'2',definition:'CAN_L'}]}],devices:[]},{id:'legacy-dst',name:'目标',type:'component',x:600,y:100,w:180,h:130,connectors:[{id:'legacy-jd',name:'J2',side:'left',pins:[{id:'legacy-dh',no:'1',definition:'CAN_H'},{id:'legacy-dl',no:'2',definition:'CAN_L'}]}],devices:[]}],connections:[{id:'legacy-can-wire',from:'pin:legacy-sh',type:'can',gauge:'0.35 mm²',targets:[{id:'legacy-can-target',to:'pin:legacy-dh'}]}],revisions:[]}));const migratedCan=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections[0]);assert.ok(!migratedCan.pairFrom);assert.ok(!migratedCan.targets[0].pairTo);assert.equal(await page.locator('[data-wire-branch="legacy-can-wire:legacy-can-target"] path.sch-can-low').count(),0);assert.equal(await page.locator('[data-wire-id="legacy-can-wire"].sch-can-incomplete').count(),1);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'invalid-twisted-group'},components:[{id:'tp3',name:'三芯错误',type:'component',x:100,y:100,w:180,h:140,connectors:[{id:'tp3j',name:'J1',side:'right',pins:[1,2,3].map(n=>({id:`tp3p${n}`,no:String(n),definition:`SIG_${n}`,twisted:true,pairGroup:'5'}))}],devices:[]}],connections:[],revisions:[]}));assert.match(await page.locator('.sch-twisted-error').textContent(),/当前有 3 个Pin，应为2个/);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({schemaVersion:6,meta:{title:'pin-label-layout'},components:[{id:'relay-layout',name:'继电器',type:'device',symbolType:'relay',x:220,y:130,w:116,h:92,connectors:[{id:'relay-left',name:'主触点输入',side:'left',pins:[{id:'relay-p1',no:'1',definition:'1'}]},{id:'relay-right',name:'主触点输出',side:'right',pins:[{id:'relay-p2',no:'2',definition:'2'}]},{id:'relay-coil',name:'线圈',side:'bottom',pins:[{id:'relay-a1',no:'A1',definition:'A1'},{id:'relay-a2',no:'A2',definition:'A2'}]}],devices:[]},{id:'pyro-layout',name:'Pyro-fuse',type:'device',symbolType:'pyro',x:480,y:120,w:180,h:140,connectors:[{id:'pyro-left',name:'输入',side:'left',pins:[{id:'pyro-in',no:'1',definition:'IN'}]},{id:'pyro-right',name:'输出',side:'right',pins:[{id:'pyro-out',no:'2',definition:'OUT'}]},{id:'pyro-bottom',name:'诊断',side:'bottom',pins:[{id:'pyro-b1',no:'3',definition:'Pin 1'},{id:'pyro-b2',no:'4',definition:'Pin 2'}]}],devices:[]}],connections:[],revisions:[]}));const labelGeometry=await page.evaluate(()=>{const point=id=>{const g=document.querySelector(`[data-pin-id="${id}"]`),circle=g.querySelector('circle'),text=g.querySelector('text');return{cx:Number(circle.getAttribute('cx')),cy:Number(circle.getAttribute('cy')),x:Number(text.getAttribute('x')),y:Number(text.getAttribute('y'))};},title=document.querySelector('[data-drag-component="pyro-layout"] .sch-device-node-title');return{p1:point('relay-p1'),p2:point('relay-p2'),a1:point('relay-a1'),a2:point('relay-a2'),pin1:point('pyro-b1'),pin2:point('pyro-b2'),titleY:Number(title.getAttribute('y'))};});assert.ok(labelGeometry.p1.x<labelGeometry.p1.cx&&labelGeometry.p2.x>labelGeometry.p2.cx);assert.ok(labelGeometry.a1.x<labelGeometry.a1.cx&&labelGeometry.a2.x>labelGeometry.a2.cx);assert.ok(labelGeometry.pin1.y>labelGeometry.pin1.cy&&labelGeometry.pin2.y>labelGeometry.pin2.cy);assert.ok(labelGeometry.titleY>labelGeometry.pin1.y);if(process.env.PIN_LABEL_SCREENSHOT)await page.locator('#schCanvas').screenshot({path:process.env.PIN_LABEL_SCREENSHOT});
await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'multi-target-exact-pin'},components:[{id:'src',name:'源',type:'component',x:100,y:100,w:160,h:140,connectors:[{id:'js',name:'J1',side:'right',pins:[{id:'psh',no:'1',definition:'SIG_P',twisted:true,pairGroup:'7'},{id:'psl',no:'2',definition:'SIG_N',twisted:true,pairGroup:'7'}]}],devices:[]},{id:'ta',name:'目标A',type:'component',x:600,y:80,w:160,h:120,connectors:[{id:'ja',name:'J2',side:'left',pins:[{id:'ptah',no:'1',definition:'SENSE_P',twisted:true,pairGroup:'3'},{id:'ptal',no:'2',definition:'SENSE_N',twisted:true,pairGroup:'3'}]}],devices:[]},{id:'tb',name:'目标B',type:'component',x:600,y:300,w:160,h:120,connectors:[{id:'jb',name:'J3',side:'left',pins:[{id:'ptbh',no:'1',definition:'DATA_P',twisted:true,pairGroup:'9'},{id:'ptbl',no:'2',definition:'DATA_N',twisted:true,pairGroup:'9'}]}],devices:[]}],connections:[{id:'wm',from:'pin:psh',pairFrom:'pin:psl',type:'can',gauge:'0.35 mm²',targets:[{id:'m1',to:'pin:ptah',pairTo:'pin:ptal',waypoints:[]},{id:'m2',to:'pin:ptbh',pairTo:'pin:ptbl',waypoints:[]}]}],revisions:[]}));const selectedHigh=await page.locator('[data-endpoint-key="pin:psh"] circle').evaluate(el=>[Number(el.getAttribute('cx')),Number(el.getAttribute('cy'))]),selectedLow=await page.locator('[data-endpoint-key="pin:psl"] circle').evaluate(el=>[Number(el.getAttribute('cx')),Number(el.getAttribute('cy'))]),highStarts=await page.locator('[data-wire-branch^="wm:"] > .sch-can-high').evaluateAll(paths=>paths.map(p=>p.getAttribute('d').match(/^M([\d.]+) ([\d.]+)/).slice(1).map(Number))),lowStarts=await page.locator('[data-wire-branch^="wm:"] > .sch-can-low').evaluateAll(paths=>paths.map(p=>p.getAttribute('d').match(/^M([\d.]+) ([\d.]+)/).slice(1).map(Number)));assert.ok(highStarts.every(([x,y])=>x===selectedHigh[0]&&y===selectedHigh[1]),'all first-core branches must start from the selected first Pin');assert.ok(lowStarts.every(([x,y])=>x===selectedLow[0]&&y===selectedLow[1]),'all second-core branches must start from the selected paired Pin');
await page.evaluate(()=>{const draft=ElectricalToolkit.get('schematic').captureDraft();draft.connections=[];ElectricalToolkit.get('schematic').restoreDraft(draft);});await page.locator('#schCanvas').scrollIntoViewIfNeeded();await page.evaluate(()=>{const from=document.querySelector('[data-endpoint-key="pin:psl"] circle'),to=document.querySelector('[data-endpoint-key="pin:ptbh"] circle'),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),ax=a.left+a.width/2,ay=a.top+a.height/2,bx=b.left+b.width/2,by=b.top+b.height/2;from.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:ax,clientY:ay}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:bx,clientY:by}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:bx,clientY:by}));});const directCan=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().connections[0]);assert.equal(directCan.from,'pin:psl');assert.equal(directCan.pairFrom,'pin:psh');assert.equal(directCan.targets[0].to,'pin:ptbh');assert.equal(directCan.targets[0].pairTo,'pin:ptbl');assert.equal(await page.locator('.sch-can-row').count(),1);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'connector-spacing'},components:[{id:'multi',name:'多连接器部件',type:'component',x:100,y:100,w:220,h:150,connectors:[{id:'j1',name:'J1',side:'right',pins:Array.from({length:5},(_,i)=>({id:`j1p${i}`,no:String(i+1),definition:`A${i+1}`}))},{id:'j2',name:'J2',side:'right',pins:Array.from({length:4},(_,i)=>({id:`j2p${i}`,no:String(i+1),definition:`B${i+1}`}))}],devices:[]}],connections:[],revisions:[]}));const pinYs=await page.locator('[data-drag-component="multi"] .sch-pin circle').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('cy'))));assert.equal(new Set(pinYs).size,pinYs.length);assert.ok(pinYs.slice(1).every((y,i)=>y-pinYs[i]>=26));assert.ok(Number(await page.locator('[data-move-component="multi"]').getAttribute('height'))>150);assert.deepEqual(errors,[]);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({meta:{title:'junction-and-pin-nudge'},components:[{id:'junction-source',name:'源部件',type:'component',x:100,y:100,w:180,h:140,connectors:[{id:'junction-js',name:'J1',side:'right',pins:[{id:'junction-pa',no:'1',definition:'SIG'}]}],devices:[]},{id:'junction-target',name:'目标部件',type:'component',x:700,y:100,w:180,h:140,connectors:[{id:'junction-jt',name:'J2',side:'left',pins:[{id:'junction-pb',no:'1',definition:'SIG'}]}],devices:[]},{id:'junction-branch',name:'分支部件',type:'component',x:700,y:360,w:180,h:140,connectors:[{id:'junction-jb',name:'J3',side:'left',pins:[{id:'junction-pc',no:'1',definition:'SIG'}]}],devices:[]}],connections:[{id:'junction-wire',from:'pin:junction-pa',type:'lv',gauge:'0.5 mm²',net:'SIG',function:'信号',targets:[{id:'junction-target-wire',to:'pin:junction-pb',waypoints:[]}]}],revisions:[]}));
  const movablePin=page.locator('[data-endpoint-key="pin:junction-pa"] circle'),pinBefore=await movablePin.evaluate(el=>({x:Number(el.getAttribute('cx')),y:Number(el.getAttribute('cy'))}));await movablePin.dispatchEvent('pointerdown');await movablePin.dispatchEvent('pointerup');assert.equal(await page.locator('[data-endpoint-key="pin:junction-pa"]').evaluate(el=>el.classList.contains('sch-pin-selected')),true);await page.keyboard.press('ArrowDown');await page.keyboard.press('Shift+ArrowDown');await page.keyboard.press('ArrowRight');const pinAfter=await page.locator('[data-endpoint-key="pin:junction-pa"] circle').evaluate(el=>({x:Number(el.getAttribute('cx')),y:Number(el.getAttribute('cy'))}));assert.equal(pinAfter.x,pinBefore.x);assert.equal(pinAfter.y,pinBefore.y+11);assert.equal(await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().components[0].connectors[0].pins[0].offset),11);
  await page.locator('[data-wire-id="junction-wire"] [data-add-junction-target="junction-target-wire"]').click();assert.equal(await page.locator('#schJunctions .sch-junction-editor').count(),1);const junctionState=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft()),junction=junctionState.components.find(c=>c.type==='junction'),junctionKey=`pin:${junction.connectors[0].pins[0].id}`;assert.equal(junctionState.connections.length,2);assert.equal(junctionState.connections.find(w=>w.id==='junction-wire').targets[0].to,junctionKey);const junctionOutgoing=junctionState.connections.find(w=>w.from===junctionKey);assert.equal(junctionOutgoing.targets[0].to,'pin:junction-pb');assert.equal(junctionOutgoing.gauge,'0.5 mm²');await page.locator(`[data-component-editor="${junction.id}"] [data-component-field="name"]`).fill('分支点 J1');assert.equal(await page.locator(`[data-drag-component="${junction.id}"] .sch-junction-label`).textContent(),'分支点 J1');
  await page.locator(`[data-wire-id="${junctionOutgoing.id}"] [data-add-target]`).click();await page.locator(`[data-wire-id="${junctionOutgoing.id}"] [data-endpoint-role="target"][data-endpoint-level="component"]`).last().selectOption('junction-branch');const branchedState=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft()),branchedWire=branchedState.connections.find(w=>w.from===junctionKey);assert.ok(branchedWire.targets.some(t=>t.to==='pin:junction-pc'));assert.equal(branchedWire.gauge,'0.5 mm²');await page.locator(`[data-wire-segment^="${junctionOutgoing.id}:"]`).first().evaluate(el=>{const r=el.getBoundingClientRect();el.dispatchEvent(new MouseEvent('dblclick',{bubbles:true,cancelable:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2}));});assert.equal(await page.locator('#schJunctions .sch-junction-editor').count(),2);assert.deepEqual(errors,[]);
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({
    schemaVersion:6,meta:{title:'workspace-grouping'},connections:[],revisions:[],components:[
      {id:'lv-first',name:'低压接口',type:'external-lv',x:900,y:100,w:180,h:130,connectors:[],devices:[]},
      {id:'part-one',name:'部件一',type:'component',x:100,y:100,w:260,h:220,connectors:[],devices:[
        {id:'inner-fuse-1',type:'fuse',name:'保险丝1',x:20,y:50,ports:['1','2']},
        {id:'inner-relay',type:'relay',name:'继电器',x:130,y:50,ports:['1','2','A1','A2']},
        {id:'inner-fuse-2',type:'fuse',name:'保险丝2',x:20,y:130,ports:['1','2']}
      ]},
      {id:'fuse-one',name:'保险丝1',type:'device',symbolType:'fuse',x:420,y:100,w:104,h:76,connectors:[],devices:[]},
      {id:'relay-one',name:'继电器1',type:'device',symbolType:'relay',x:560,y:100,w:116,h:92,connectors:[],devices:[]},
      {id:'fuse-two',name:'保险丝2',type:'device',symbolType:'fuse',x:700,y:100,w:104,h:76,connectors:[],devices:[]},
      {id:'part-two',name:'部件二',type:'component',x:100,y:380,w:260,h:180,connectors:[],devices:[]},
      {id:'hv-later',name:'高压接口',type:'external-hv',x:900,y:300,w:180,h:130,connectors:[],devices:[]},
      {id:'resistor-last',name:'电阻',type:'device',symbolType:'resistor',x:700,y:260,w:104,h:76,connectors:[],devices:[]}
    ]
  }));
  const editorTypes=selector=>page.locator(selector).evaluateAll(nodes=>nodes.map(node=>node.value));
  assert.deepEqual(await editorTypes('#schComponents > details [data-component-field="type"]'),['component','component','external-hv','external-lv']);
  assert.deepEqual(await editorTypes('#schStandaloneDevices > details [data-component-field="symbolType"]'),['relay','fuse','fuse','resistor']);
  assert.deepEqual(await editorTypes('[data-component-editor="part-one"] [data-device-field="type"]'),['relay','fuse','fuse']);
  await page.locator('[data-palette-type="fuse"]').click();
  assert.deepEqual(await editorTypes('#schStandaloneDevices > details [data-component-field="symbolType"]'),['relay','fuse','fuse','fuse','resistor']);
  await page.locator('#schAddComponent').click();await page.locator('#schAddExternal').click();
  assert.deepEqual(await editorTypes('#schComponents > details [data-component-field="type"]'),['component','component','component','external-hv','external-lv','external-lv']);
  const dragWorkspace=async(sourceId,targetId,after=false)=>page.evaluate(({sourceId,targetId,after})=>{const source=document.querySelector(`[data-workspace-drag="${sourceId}"]`),target=document.querySelector(`[data-component-editor="${targetId}"]`),dt=new DataTransfer(),r=target.getBoundingClientRect(),clientX=r.left+20,clientY=after?r.bottom-2:r.top+2;source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt,clientX,clientY}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt,clientX,clientY}));},{sourceId,targetId,after});
  await dragWorkspace('lv-first','part-one');assert.equal(await page.locator('#schComponents > details').first().getAttribute('data-component-editor'),'lv-first');
  await dragWorkspace('resistor-last','relay-one');assert.equal(await page.locator('#schStandaloneDevices > details').first().getAttribute('data-component-editor'),'resistor-last');
  const manuallyOrdered=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft());assert.ok(manuallyOrdered.components.every(c=>Number.isFinite(c.workspaceOrder)));await page.evaluate(saved=>ElectricalToolkit.get('schematic').restoreDraft(saved),manuallyOrdered);assert.equal(await page.locator('#schComponents > details').first().getAttribute('data-component-editor'),'lv-first');assert.equal(await page.locator('#schStandaloneDevices > details').first().getAttribute('data-component-editor'),'resistor-last');
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({schemaVersion:6,meta:{title:'compact-one-pin'},components:[{id:'compact-part',name:'FPC1',type:'component',x:200,y:140,w:180,h:120,connectors:[{id:'compact-j1',name:'J1',side:'right',pins:[{id:'compact-p1',no:'1',definition:'Pin 1'}]}],devices:[]}],connections:[],revisions:[]}));
  await page.locator('[data-resize-component="compact-part"]').evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:x,clientY:y}));document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:x-500,clientY:y-500}));document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:x-500,clientY:y-500}));});
  const compactPart=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft().components[0]);assert.equal(compactPart.w,100);assert.equal(compactPart.h,60);assert.equal(await page.locator('[data-drag-component="compact-part"]').evaluate(el=>el.classList.contains('sch-compact-component')),true);assert.equal(await page.locator('[data-component-editor="compact-part"] [data-component-field="h"]').getAttribute('min'),'60');if(process.env.COMPACT_COMPONENT_SCREENSHOT)await page.locator('#schCanvas').screenshot({path:process.env.COMPACT_COMPONENT_SCREENSHOT});
  await page.evaluate(()=>ElectricalToolkit.get('schematic').restoreDraft({
    schemaVersion:6,
    meta:{title:'clone-component'},
    components:[
      {id:'clone-source',name:'EDM',type:'component',x:100,y:100,w:300,h:220,connectors:[{id:'clone-j1',name:'J1',side:'right',pins:[{id:'clone-p1',no:'1',definition:'HV+'}]}],devices:[{id:'clone-relay',type:'relay',name:'主继电器',value:'MC+',x:50,y:70,ports:['1','2','A1','A2']}]},
      {id:'clone-target',name:'负载',type:'component',x:800,y:100,w:180,h:120,connectors:[{id:'clone-j2',name:'J2',side:'left',pins:[{id:'clone-p2',no:'1',definition:'HV+'}]}],devices:[]}
    ],
    connections:[{id:'clone-wire',from:'pin:clone-p1',type:'hv',gauge:'25 mm²',targets:[{id:'clone-target-wire',to:'pin:clone-p2',waypoints:[]}]}],
    revisions:[]
  }));
  await page.locator('[data-component-editor="clone-source"] [data-clone-component]').click();
  const clonedState=await page.evaluate(()=>ElectricalToolkit.get('schematic').captureDraft()),clonedPart=clonedState.components.find(c=>c.name==='EDM 副本'),sourcePart=clonedState.components.find(c=>c.id==='clone-source');
  assert.equal(clonedState.components.length,3);assert.equal(clonedState.connections.length,1);assert.ok(clonedPart);assert.notEqual(clonedPart.id,sourcePart.id);assert.ok(clonedPart.x!==sourcePart.x||clonedPart.y!==sourcePart.y);assert.equal(clonedPart.connectors[0].name,'J1');assert.notEqual(clonedPart.connectors[0].id,sourcePart.connectors[0].id);assert.notEqual(clonedPart.connectors[0].pins[0].id,sourcePart.connectors[0].pins[0].id);assert.equal(clonedPart.devices[0].name,'主继电器');assert.notEqual(clonedPart.devices[0].id,sourcePart.devices[0].id);assert.equal(await page.locator(`[data-drag-component="${clonedPart.id}"]`).evaluate(el=>el.classList.contains('sch-selected')),true);
  await browser.close();console.log('PASS schematic generator: components, pins, devices, wires, JSON, SVG and PDF');
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
