const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '..');
let browser;
(async () => {
  browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless:true,
    args:['--allow-file-access-from-files','--disable-gpu','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport:{ width:1500, height:1000 } });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(pathToFileURL(path.join(root, 'index.html')).href);
  await page.evaluate(() => ElectricalToolkit.open('standards-library'));
  await page.waitForSelector('.sl-card');
  const total = await page.evaluate(() => ELECTRICAL_STANDARD_LIBRARY.records.length);
  assert.ok(total >= 80, 'library has broad coverage including LV and USCAR systems');
  assert.equal(await page.locator('.sl-card', { hasText:'GB/T 37133-2018' }).count(), 0, 'history hidden by default');
  await page.locator('#slQuery').fill('热扩散');
  assert.ok(await page.locator('.sl-card').count() >= 2, 'full text search works');
  await page.locator('#slQuery').fill('');
  await page.locator('#slTopic').selectOption('换电系统');
  const topics = await page.locator('.sl-card .sl-topic').allTextContents();
  assert.ok(topics.length >= 10 && topics.every((item) => item === '换电系统'), 'topic filtering works');
  await page.locator('#slSystem').selectOption('IEC');
  assert.ok(await page.locator('.sl-card').count() >= 3, 'combined filters work');
  await page.locator('#slHistory').check();
  await page.locator('#slSystem').selectOption('GB');
  assert.ok(await page.locator('.sl-card', { hasText:'GB/T 32879-2016' }).count() === 1, 'history can be shown');
  await page.locator('[data-view=table]').click();
  assert.ok(await page.locator('.sl-table tbody tr').count() >= 3, 'table view works');
  await page.locator('#slClear').click();
  assert.equal(await page.locator('#slHistory').isChecked(), false);
  assert.ok((await page.locator('#slCount').textContent()).includes(String(total)));
  await page.locator('#slSystem').selectOption('LV');
  assert.ok(await page.locator('.sl-card').count() >= 10, 'LV connector system is covered');
  await page.locator('#slSystem').selectOption('USCAR');
  assert.ok(await page.locator('.sl-card').count() >= 14, 'USCAR/EWCAP connector system is covered');
  assert.equal(await page.locator('.sl-card', { hasText:'SAE/USCAR-37' }).count(), 1, 'USCAR high-voltage supplement is present');
  await page.locator('#slSystem').selectOption('全部');
  const hrefs = await page.locator('.sl-card-actions a').evaluateAll((links) => links.map((a) => a.href));
  assert.ok(hrefs.every((href) => /^https:\/\/(openstd\.samr\.gov\.cn|www\.iso\.org|webstore\.iec\.ch|unece\.org|www\.dakks\.de|www\.edag\.com|uscar\.org)\//.test(href)), 'all sources are official publishers, industry bodies, or accredited scope indexes');
  assert.deepEqual(errors, []);
  await page.screenshot({ path:path.join(root,'tmp','standards-library-qa.png'), fullPage:true });
  await browser.close(); console.log(`PASS standards library: ${total} records`);
})().catch(async (error) => { console.error(error); if (browser) await browser.close(); process.exitCode = 1; });
