/** Pure routing. Project operations return routes or patches; callers apply them. */
(function(root,factory){
  const common=typeof module==='object'&&module.exports;
  const api=factory(common?require('./model.js'):root.ElectricalSchematic.model,common?require('./geometry.js'):root.ElectricalSchematic.geometry);
  if(common)module.exports=api;else root.ElectricalSchematic.routing=api;
})(typeof globalThis==='object'?globalThis:this,function(M,G){
  'use strict';
  const {clamp,clone,connectorIsPlaced}=M;
  const {isHorizontal,overlaps,pointSegmentDistance,canvasDimensions,snapCoordinate,snapClamp,outward,endpointPositions}=G;
  function keepOutside(q,p,distance=10){q={...q};if(q.junctionId)return q;if(p.side==='left')q.x=Math.min(q.x,p.x-distance);else if(p.side==='right')q.x=Math.max(q.x,p.x+distance);else if(p.side==='top')q.y=Math.min(q.y,p.y-distance);else if(p.side==='bottom')q.y=Math.max(q.y,p.y+distance);return q;}
  function simplify(points){const out=[];for(const p of points){const last=out[out.length-1];if(last&&last.x===p.x&&last.y===p.y){if(p.junctionId&&!last.junctionId)out[out.length-1]=p;continue;}out.push(p);while(out.length>=3){const a=out[out.length-3],b=out[out.length-2],c=out[out.length-1];if(!b.junctionId&&((a.x===b.x&&b.x===c.x)||(a.y===b.y&&b.y===c.y)))out.splice(out.length-2,1);else break;}}return out;}
  function wireText(w){return[w.net,w.gauge,w.function].filter(value=>String(value||'').trim()).join(' · ');}
  function startLabelPoint(route,width,height){for(let i=0;i<route.length-1;i++){const a=route[i],b=route[i+1];if(a.x===b.x&&a.y!==b.y)return{x:a.x-width-7,y:Math.min(a.y,b.y)+7,lineX:a.x,lineY:a.y,vertical:true};if(isHorizontal(a,b)){const right=b.x>=a.x,x=right?a.x+8:a.x-width-8;return{x,y:a.y-height-5,lineX:a.x,lineY:a.y,minX:Math.min(a.x,b.x)+5,maxX:Math.max(a.x,b.x)-width-5,vertical:false};}}const a=route[0]||{x:20,y:50};return{x:a.x+10,y:a.y-height-5,lineX:a.x,lineY:a.y,minX:a.x+5,maxX:a.x+240,vertical:false};}
  function collinearOverlap(a,b){let score=0;for(let i=0;i<a.length-1;i++)for(let j=0;j<b.length-1;j++){const a1=a[i],a2=a[i+1],b1=b[j],b2=b[j+1];if(isHorizontal(a1,a2)&&isHorizontal(b1,b2)&&a1.y===b1.y)score+=Math.max(0,Math.min(Math.max(a1.x,a2.x),Math.max(b1.x,b2.x))-Math.max(Math.min(a1.x,a2.x),Math.min(b1.x,b2.x)));else if(!isHorizontal(a1,a2)&&!isHorizontal(b1,b2)&&a1.x===a2.x&&b1.x===b2.x)score+=Math.max(0,Math.min(Math.max(a1.y,a2.y),Math.max(b1.y,b2.y))-Math.max(Math.min(a1.y,a2.y),Math.min(b1.y,b2.y)));}return score;}
  function routeScore(route,placed){return placed.reduce((score,item)=>score+collinearOverlap(route,item.route)*20,0);}
  function crossingMap(routes){const map=new Map(routes.map(r=>[r.id,new Map()]));for(let i=0;i<routes.length;i++)for(let j=i+1;j<routes.length;j++){const ra=routes[i],rb=routes[j];for(let ai=0;ai<ra.route.length-1;ai++)for(let bi=0;bi<rb.route.length-1;bi++){const a1=ra.route[ai],a2=ra.route[ai+1],b1=rb.route[bi],b2=rb.route[bi+1];let h1,h2,v1,v2,hRoute,hSeg,vRoute,vSeg;if(isHorizontal(a1,a2)&&!isHorizontal(b1,b2)&&b1.x===b2.x){h1=a1;h2=a2;v1=b1;v2=b2;hRoute=ra;hSeg=ai;vRoute=rb;vSeg=bi;}else if(isHorizontal(b1,b2)&&!isHorizontal(a1,a2)&&a1.x===a2.x){h1=b1;h2=b2;v1=a1;v2=a2;hRoute=rb;hSeg=bi;vRoute=ra;vSeg=ai;}else continue;const x=v1.x,y=h1.y;if(x>Math.min(h1.x,h2.x)+8&&x<Math.max(h1.x,h2.x)-8&&y>Math.min(v1.y,v2.y)+8&&y<Math.max(v1.y,v2.y)-8){const chosen=hRoute.index>vRoute.index?{r:hRoute,s:hSeg,p:{x,y}}:{r:vRoute,s:vSeg,p:{x,y}};const sm=map.get(chosen.r.id);if(!sm.has(chosen.s))sm.set(chosen.s,[]);sm.get(chosen.s).push(chosen.p);}}}return map;}
  function offsetRoute(route,off){return route.map((p,i)=>{if(i===0||i===route.length-1)return{x:p.x,y:p.y};const prev=route[i-1],next=route[i+1],vertical=(prev&&prev.x===p.x)||(next&&next.x===p.x),horizontal=(prev&&prev.y===p.y)||(next&&next.y===p.y);return{x:p.x+(vertical?off:0),y:p.y+(horizontal?off:0)};});}
  function shiftedCrossings(route,map,off){const out=new Map();map?.forEach((pts,si)=>{const a=route[si],b=route[si+1],horizontal=isHorizontal(a,b);out.set(si,pts.map(p=>({x:p.x+(horizontal?0:off),y:p.y+(horizontal?off:0)})));});return out;}
  function pathWithBridges(route,map){if(!route.length)return'';let d=`M${route[0].x} ${route[0].y}`;for(let i=0;i<route.length-1;i++){const a=route[i],b=route[i+1],horizontal=isHorizontal(a,b),forward=horizontal?b.x>a.x:b.y>a.y,pts=(map?.get(i)||[]).slice().sort((p,q)=>(horizontal?p.x-q.x:p.y-q.y)*(forward?1:-1));for(const p of pts){if(horizontal)d+=` L${p.x+(forward?-6:6)} ${p.y} A6 6 0 0 ${forward?1:0} ${p.x+(forward?6:-6)} ${p.y}`;else d+=` L${p.x} ${p.y+(forward?-6:6)} A6 6 0 0 ${forward?0:1} ${p.x} ${p.y+(forward?6:-6)}`;}d+=` L${b.x} ${b.y}`;}return d;}
  function labelPoint(route){let best={len:0,x:route[0]?.x||0,y:route[0]?.y||0,horizontal:false};for(let i=0;i<route.length-1;i++){const a=route[i],b=route[i+1],horizontal=isHorizontal(a,b),len=Math.abs(b.x-a.x)+Math.abs(b.y-a.y);if((horizontal&&!best.horizontal)||(horizontal===best.horizontal&&len>best.len))best={len,x:(a.x+b.x)/2,y:(a.y+b.y)/2,horizontal};}return best;}
  function branchMidpoint(state,branch){let best={length:-1,segmentIndex:0,x:branch.route[0]?.x||100,y:branch.route[0]?.y||100};for(let i=0;i<branch.route.length-1;i++){const a=branch.route[i],b=branch.route[i+1],length=Math.abs(b.x-a.x)+Math.abs(b.y-a.y);if(length>best.length)best={length,segmentIndex:i,x:snapCoordinate(state,(a.x+b.x)/2),y:snapCoordinate(state,(a.y+b.y)/2)};}return best;}
  function manualRoute(state,a,b,sa,sb,waypoints){const points=[{x:a.x,y:a.y}],controls=waypoints.map(p=>({...p})),append=raw=>{const free=raw.free===true,q={...raw,x:snapCoordinate(state,raw.x,free),y:snapCoordinate(state,raw.y,free)},last=points[points.length-1];if(last.x!==q.x&&last.y!==q.y)points.push({x:q.x,y:last.y});points.push(q);};if(controls.length){controls[0]=keepOutside(controls[0],a);controls[controls.length-1]=keepOutside(controls[controls.length-1],b);}if(!a.junction)points.push(sa);controls.forEach(append);if(!b.junction)append(sb);points.push({x:b.x,y:b.y});return simplify(points);}
  function routePoints(state,a,b,rank,count,branchIndex,channelAdjust=0,waypoints=[]){const {w:cw,h:ch}=canvasDimensions(state),gap=30,channel=rank+channelAdjust,lane=(channel-(count-1)/2)*gap,depth=rank+Math.abs(channelAdjust),escape=40+depth*20+branchIndex*10,sa=outward(state,a,escape),sb=outward(state,b,40+depth*20),aHorizontal=a.side==='left'||a.side==='right',bHorizontal=b.side==='left'||b.side==='right';if(waypoints.length)return manualRoute(state,a,b,sa,sb,waypoints);let middle;if(aHorizontal&&bHorizontal){const x=snapClamp(state,(sa.x+sb.x)/2+lane,20,cw-20);middle=[{x,y:sa.y},{x,y:sb.y}];}else if(!aHorizontal&&!bHorizontal){const y=snapClamp(state,(sa.y+sb.y)/2+lane,50,ch-90);middle=[{x:sa.x,y},{x:sb.x,y}];}else if(aHorizontal){const dir=a.side==='right'?1:-1,x=snapClamp(state,sa.x+dir*(40+depth*gap),20,cw-20);middle=[{x,y:sa.y},{x,y:sb.y},{x:sb.x,y:sb.y}];}else{const dir=a.side==='bottom'?1:-1,y=snapClamp(state,sa.y+dir*(40+depth*gap),50,ch-90);middle=[{x:sa.x,y},{x:sb.x,y},{x:sb.x,y:sb.y}];}return simplify([{x:a.x,y:a.y},sa,...middle,sb,{x:b.x,y:b.y}]);}
  function assignLabelBoxes(state,items){
    const {w:cw,h:ch}=canvasDimensions(state),placed=[],seen=new Set;
    const place=(route,text,atEnd=false)=>{
      const width=clamp(Array.from(text).reduce((n,ch)=>n+(/[\u0100-\uffff]/.test(ch)?7.5:4.9),4),24,300),height=12,ordered=atEnd?[...route].reverse():route;
      let anchor=startLabelPoint(ordered,width,height);
      if(atEnd&&anchor.vertical){const a=ordered[0],b=ordered.find(p=>p.x!==a.x||p.y!==a.y);if(b)anchor={...anchor,y:b.y>=a.y?a.y+7:a.y-height-7,lineY:a.y};}
      let box;
      if(anchor.vertical){const baseY=clamp(anchor.y,8,ch-height-105),x=clamp(anchor.x,8,cw-width-8);box={x,y:baseY,w:width,h:height};for(const shift of [18,-18,36,-36,54,-54]){if(!placed.some(other=>overlaps(box,other,2)))break;box={x,y:clamp(baseY+shift,8,ch-height-105),w:width,h:height};}}
      else{const minX=clamp(Math.min(anchor.minX,anchor.maxX),8,cw-width-8),maxX=clamp(Math.max(anchor.minX,anchor.maxX),8,cw-width-8),baseX=clamp(anchor.x,minX,maxX),y=clamp(anchor.y,8,ch-105);box={x:baseX,y,w:width,h:height};for(const shift of [30,-30,60,-60,90,-90,120,-120]){if(!placed.some(other=>overlaps(box,other,2)))break;box={x:clamp(baseX+shift,minX,maxX),y,w:width,h:height};}}
      placed.push(box);return{...box,text,lineY:anchor.lineY,vertical:anchor.vertical};
    };
    items.forEach(item=>{
      delete item.label;delete item.endGaugeLabel;
      const wire=item.wire,mode=wire.gaugeLabelPosition||'start';
      if(!seen.has(wire.id)){
        seen.add(wire.id);
        const text=mode==='end'?[wire.net,wire.function].filter(value=>String(value||'').trim()).join(' · '):wireText(wire);
        if(text)item.label=place(item.route,text);
      }
      if((mode==='end'||mode==='both')&&String(wire.gauge||'').trim())item.endGaugeLabel=place(item.route,String(wire.gauge),true);
    });
  }
  function branches(state,pos){
    const raw=[];state.connections.forEach(w=>w.targets.forEach((t,ti)=>{const a=pos[w.from],b=pos[t.to],pairA=w.type==='can'?pos[w.pairFrom]:null,pairB=w.type==='can'?pos[t.pairTo]:null;if(a&&b&&(w.type!=='can'||pairA&&pairB))raw.push({id:`${w.id}:${t.id}`,wire:w,target:t,targetIndex:ti,a,b,pairA,pairB,group:`${a.side}:${b.side}`});}));
    const counts={};raw.forEach(r=>counts[r.group]=(counts[r.group]||0)+1);const ranks={},out=[];
    raw.forEach((r,index)=>{const rank=ranks[r.group]||0;ranks[r.group]=rank+1;const manual=Array.isArray(r.target.waypoints)&&r.target.waypoints.length;let route,adjust=0;if(manual)route=routePoints(state,r.a,r.b,rank,counts[r.group],r.targetIndex,0,r.target.waypoints);else{let bestScore=Infinity;for(const candidateAdjust of [0,1,-1,2,-2,3,-3,4,-4]){const candidate=routePoints(state,r.a,r.b,rank,counts[r.group],r.targetIndex,candidateAdjust,[]),score=routeScore(candidate,out);if(score<bestScore){bestScore=score;route=candidate;adjust=candidateAdjust;}if(score===0)break;}}let pairRoute;if(r.wire.type==='can'){const pairWaypoints=manual?r.target.waypoints.map(p=>({x:p.x+6,y:p.y+6,...(p.free===true?{free:true}:{})})):[];pairRoute=routePoints(state,r.pairA,r.pairB,rank,counts[r.group],r.targetIndex,adjust+.2,pairWaypoints);}out.push({...r,index,rank,manual:Boolean(manual),route,pairRoute});});assignLabelBoxes(state,out);return out;
  }
  function ensureJunctionBindings(state){const pending=state.connections.filter(child=>child.parentWireId&&child.parentTargetId&&child.parentJunctionId).filter(child=>{const parent=state.connections.find(w=>w.id===child.parentWireId),t=parent?.targets.find(item=>item.id===child.parentTargetId);return t&&!(t.waypoints||[]).some(p=>p.junctionId===child.parentJunctionId);});if(!pending.length)return;const current=branches(state,endpointPositions(state));pending.forEach(child=>{const parent=state.connections.find(w=>w.id===child.parentWireId),t=parent?.targets.find(item=>item.id===child.parentTargetId),junction=state.components.find(c=>c.id===child.parentJunctionId);if(!parent||!t||!junction)return;t.waypoints=t.waypoints||[];const branch=current.find(item=>item.wire.id===parent.id&&item.target.id===t.id);if(!branch?.route?.length){t.waypoints.push({x:junction.x,y:junction.y,junctionId:junction.id});return;}let segmentIndex=0,best=Infinity;for(let i=0;i<branch.route.length-1;i++){const distance=pointSegmentDistance(junction,branch.route[i],branch.route[i+1]);if(distance<best){best=distance;segmentIndex=i;}}const route=branch.route.map(p=>({...p}));route.splice(segmentIndex+1,0,{x:junction.x,y:junction.y,junctionId:junction.id});t.waypoints=route.slice(1,-1);});}
  function syncJunctionWaypoints(state){const junctions=new Map(state.components.filter(c=>c.type==='junction').map(c=>[c.id,c]));state.connections.forEach(w=>w.targets.forEach(t=>(t.waypoints||[]).forEach(p=>{const junction=p.junctionId&&junctions.get(p.junctionId);if(junction){p.x=junction.x;p.y=junction.y;}})));}
  function waypointUpdates(state,operation){
    const copy=clone(state);operation(copy);const updates=[];
    copy.connections.forEach((wire,wi)=>wire.targets.forEach((target,ti)=>{
      if(JSON.stringify(target.waypoints)!==JSON.stringify(state.connections[wi].targets[ti].waypoints))updates.push({wireId:wire.id,targetId:target.id,waypoints:target.waypoints});
    }));return updates;
  }
  function labelPlacement(state,items){const copy=items.map(item=>({...item}));assignLabelBoxes(state,copy);return copy;}

  function splitBranchAt(state,branch,point,context){
    if(!branch?.wire||!branch?.target||!point)return false;
    state=clone(state);
    const uid=context.id,target=(...args)=>M.createTarget(context,...args),junctionNode=(...args)=>M.createJunction({...context,meta:state.meta},...args);
    const w=state.connections.find(item=>item.id===branch.wire.id),t=w?.targets.find(item=>item.id===branch.target.id);if(!w||!t||!point)return false;const segmentIndex=clamp(Number(point.segmentIndex)||0,0,Math.max(0,branch.route.length-2)),junction=junctionNode(point.x,point.y,w.type==='can'),pins=junction.connectors[0].pins,junctionFrom=`pin:${pins[0].id}`,junctionPair=pins[1]?`pin:${pins[1].id}`:'',route=branch.route.map(p=>({...p}));route.splice(segmentIndex+1,0,{x:junction.x,y:junction.y,junctionId:junction.id});t.waypoints=route.slice(1,-1).map(p=>({...p}));
    const nextTarget=target('');if(w.type==='can')nextTarget.pairTo='';const nextWire={id:uid('wire'),from:junctionFrom,targets:[nextTarget],type:w.type,gauge:w.gauge||'',net:w.net||'',function:w.function||'',parentWireId:w.id,parentTargetId:t.id,parentJunctionId:junction.id};if(w.gaugeLabelPosition)nextWire.gaugeLabelPosition=w.gaugeLabelPosition;if(w.type==='can')nextWire.pairFrom=junctionPair;
    state.components.push(junction);const at=state.connections.indexOf(w);state.connections.splice(at<0?state.connections.length:at+1,0,nextWire);return {state,junctionId:junction.id};
  }
  function ownsEndpoint(state,c,key){if(!key)return false;const owner=state.components.find(item=>item.connectors.filter(connectorIsPlaced).some(k=>k.pins.some(p=>key===`pin:${p.id}`))||item.devices.some(d=>d.ports.some((_,i)=>key===`device:${d.id}:${i}`)));return owner?.id===c.id;}
  function prepareAttachedRoutes(state,c){const current=branches(state,endpointPositions(state)),snapshots=[];current.forEach(branch=>{const source=ownsEndpoint(state,c,branch.wire.from)||ownsEndpoint(state,c,branch.wire.pairFrom),destination=ownsEndpoint(state,c,branch.target.to)||ownsEndpoint(state,c,branch.target.pairTo);if(!source&&!destination)return;let points=branch.target.waypoints||[];if(!points.length&&branch.route.length>2)points=branch.route.slice(1,-1);snapshots.push({wireId:branch.wire.id,targetId:branch.target.id,points:points.map(p=>({...p})),source,destination});});return snapshots;}
  function moveAttachedRoutes(snapshots,dx,dy,c){return snapshots.map(item=>{const points=item.points.map(p=>({...p})),movable=p=>!p.junctionId||p.junctionId===c.id,shift=p=>{if(!p||!movable(p))return;p.x+=dx;p.y+=dy;};if(item.source&&item.destination)points.forEach(shift);else if(item.source)shift(points[0]);else if(item.destination)shift(points[points.length-1]);return {wireId:item.wireId,targetId:item.targetId,waypoints:points};});}
  return Object.freeze({keepOutside,simplify,wireText,startLabelPoint,collinearOverlap,routeScore,crossingMap,offsetRoute,shiftedCrossings,pathWithBridges,labelPoint,branchMidpoint,manualRoute,routeBranch:routePoints,buildBranches:branches,findCrossings:crossingMap,labelPlacement,splitBranchAt,ownsEndpoint,prepareAttachedRoutes,moveAttachedRoutes,
    ensureJunctionBindings:state=>waypointUpdates(state,ensureJunctionBindings),
    syncJunctionWaypoints:state=>waypointUpdates(state,syncJunctionWaypoints)
  });
});
